// This file was auto-generated by Fern from our API Definition.

export const AuthorsGetRequestPublishedDatePrecision = {
    Full: "full",
    TimezoneUnknown: "timezone unknown",
    Date: "date",
} as const;
export type AuthorsGetRequestPublishedDatePrecision =
    (typeof AuthorsGetRequestPublishedDatePrecision)[keyof typeof AuthorsGetRequestPublishedDatePrecision];
