/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuthorsGetRequestSortBy = "relevancy" | "date" | "rank";

export const AuthorsGetRequestSortBy = {
    Relevancy: "relevancy",
    Date: "date",
    Rank: "rank",
} as const;
