/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AggregationGetRequestPublishedDatePrecision = "full" | "timezone unknown" | "date";

export const AggregationGetRequestPublishedDatePrecision = {
    Full: "full",
    TimezoneUnknown: "timezone unknown",
    Date: "date",
} as const;
