/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../../../index";

export type AggregationPostResponse =
    | NewscatcherApi.AggregationCountResponseDto
    | NewscatcherApi.FailedAggregationCountResponseDto;
