// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../index.js";

export type AggregationCountGetResponse =
    | NewscatcherApi.AggregationCountResponseDto
    | NewscatcherApi.FailedAggregationCountResponseDto;
