/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AggregationGetRequestAggregationBy = "day" | "hour";

export const AggregationGetRequestAggregationBy = {
    Day: "day",
    Hour: "hour",
} as const;
