// This file was auto-generated by Fern from our API Definition.

export const SearchSimilarGetRequestSortBy = {
    Relevancy: "relevancy",
    Date: "date",
    Rank: "rank",
} as const;
export type SearchSimilarGetRequestSortBy =
    (typeof SearchSimilarGetRequestSortBy)[keyof typeof SearchSimilarGetRequestSortBy];
