/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const LatestHeadlinesRequestIsHeadline: core.serialization.Schema<
    serializers.LatestHeadlinesRequestIsHeadline.Raw,
    NewscatcherApi.LatestHeadlinesRequestIsHeadline
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.boolean()]);

export declare namespace LatestHeadlinesRequestIsHeadline {
    type Raw = string | boolean;
}
