/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../../../../index";

/**
 * @example
 *     {
 *         lang: "en",
 *         predefinedSources: ["top 50 US", "top 20 GB"],
 *         isOpinion: false,
 *         pageSize: 10
 *     }
 */
export interface LatestHeadlinesPostRequest {
    when?: NewscatcherApi.When;
    byParseDate?: NewscatcherApi.ByParseDate;
    lang?: NewscatcherApi.Lang;
    notLang?: NewscatcherApi.NotLang;
    countries?: NewscatcherApi.Countries;
    notCountries?: NewscatcherApi.NotCountries;
    predefinedSources?: NewscatcherApi.PredefinedSources;
    sources?: NewscatcherApi.Sources;
    notSources?: NewscatcherApi.NotSources;
    notAuthorName?: NewscatcherApi.NotAuthorName;
    rankedOnly?: NewscatcherApi.RankedOnly;
    isHeadline?: NewscatcherApi.IsHeadline;
    isOpinion?: NewscatcherApi.IsOpinion;
    isPaidContent?: NewscatcherApi.IsPaidContent;
    parentUrl?: NewscatcherApi.ParentUrl;
    allLinks?: NewscatcherApi.AllLinks;
    allDomainLinks?: NewscatcherApi.AllDomainLinks;
    wordCountMin?: NewscatcherApi.WordCountMin;
    wordCountMax?: NewscatcherApi.WordCountMax;
    page?: NewscatcherApi.Page;
    pageSize?: NewscatcherApi.PageSize;
    clusteringEnabled?: NewscatcherApi.ClusteringEnabled;
    clusteringVariable?: NewscatcherApi.ClusteringVariable;
    clusteringThreshold?: NewscatcherApi.ClusteringThreshold;
    includeNlpData?: NewscatcherApi.IncludeNlpData;
    hasNlp?: NewscatcherApi.HasNlp;
    theme?: NewscatcherApi.Theme;
    notTheme?: NewscatcherApi.NotTheme;
    orgEntityName?: NewscatcherApi.OrgEntityName;
    perEntityName?: NewscatcherApi.PerEntityName;
    locEntityName?: NewscatcherApi.LocEntityName;
    miscEntityName?: NewscatcherApi.MiscEntityName;
    titleSentimentMin?: NewscatcherApi.TitleSentimentMin;
    titleSentimentMax?: NewscatcherApi.TitleSentimentMax;
    contentSentimentMin?: NewscatcherApi.ContentSentimentMin;
    contentSentimentMax?: NewscatcherApi.ContentSentimentMax;
    iptcTags?: NewscatcherApi.IptcTags;
    notIptcTags?: NewscatcherApi.NotIptcTags;
    iabTags?: NewscatcherApi.IabTags;
    notIabTags?: NewscatcherApi.NotIabTags;
    customTags?: NewscatcherApi.CustomTags;
}
