// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../../index.js";

/**
 * @example
 *     {
 *         when: "7d",
 *         page_size: 1
 *     }
 */
export interface LatestHeadlinesPostRequest {
    when?: NewscatcherApi.When;
    by_parse_date?: NewscatcherApi.ByParseDate;
    lang?: NewscatcherApi.Lang;
    not_lang?: NewscatcherApi.NotLang;
    countries?: NewscatcherApi.Countries;
    not_countries?: NewscatcherApi.NotCountries;
    predefined_sources?: NewscatcherApi.PredefinedSources;
    sources?: NewscatcherApi.Sources;
    not_sources?: NewscatcherApi.NotSources;
    not_author_name?: NewscatcherApi.NotAuthorName;
    ranked_only?: NewscatcherApi.RankedOnly;
    is_headline?: NewscatcherApi.IsHeadline;
    is_opinion?: NewscatcherApi.IsOpinion;
    is_paid_content?: NewscatcherApi.IsPaidContent;
    parent_url?: NewscatcherApi.ParentUrl;
    all_links?: NewscatcherApi.AllLinks;
    all_domain_links?: NewscatcherApi.AllDomainLinks;
    word_count_min?: NewscatcherApi.WordCountMin;
    word_count_max?: NewscatcherApi.WordCountMax;
    page?: NewscatcherApi.Page;
    page_size?: NewscatcherApi.PageSize;
    clustering_enabled?: NewscatcherApi.ClusteringEnabled;
    clustering_variable?: NewscatcherApi.ClusteringVariable;
    clustering_threshold?: NewscatcherApi.ClusteringThreshold;
    include_translation_fields?: NewscatcherApi.IncludeTranslationFields;
    include_nlp_data?: NewscatcherApi.IncludeNlpData;
    has_nlp?: NewscatcherApi.HasNlp;
    theme?: NewscatcherApi.Theme;
    not_theme?: NewscatcherApi.NotTheme;
    ORG_entity_name?: NewscatcherApi.OrgEntityName;
    PER_entity_name?: NewscatcherApi.PerEntityName;
    LOC_entity_name?: NewscatcherApi.LocEntityName;
    MISC_entity_name?: NewscatcherApi.MiscEntityName;
    title_sentiment_min?: NewscatcherApi.TitleSentimentMin;
    title_sentiment_max?: NewscatcherApi.TitleSentimentMax;
    content_sentiment_min?: NewscatcherApi.ContentSentimentMin;
    content_sentiment_max?: NewscatcherApi.ContentSentimentMax;
    iptc_tags?: NewscatcherApi.IptcTags;
    not_iptc_tags?: NewscatcherApi.NotIptcTags;
    iab_tags?: NewscatcherApi.IabTags;
    not_iab_tags?: NewscatcherApi.NotIabTags;
    custom_tags?: NewscatcherApi.CustomTags;
    robots_compliant?: NewscatcherApi.RobotsCompliant;
}
