/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as NewscatcherApi from "../index";

export class RequestTimeoutError extends errors.NewscatcherApiError {
    constructor(body: NewscatcherApi.Error_) {
        super({
            message: "RequestTimeoutError",
            statusCode: 408,
            body: body,
        });
        Object.setPrototypeOf(this, RequestTimeoutError.prototype);
    }
}
