// This file was auto-generated by Fern from our API Definition.

export const SearchGetRequestClusteringVariable = {
    Content: "content",
    Title: "title",
    Summary: "summary",
} as const;
export type SearchGetRequestClusteringVariable =
    (typeof SearchGetRequestClusteringVariable)[keyof typeof SearchGetRequestClusteringVariable];
