/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchGetRequestNewsDomainType =
    | "Original Content"
    | "Aggregator"
    | "Press Releases"
    | "Republisher"
    | "Other";
export const SearchGetRequestNewsDomainType = {
    OriginalContent: "Original Content",
    Aggregator: "Aggregator",
    PressReleases: "Press Releases",
    Republisher: "Republisher",
    Other: "Other",
} as const;
