/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchGetRequestSortBy = "relevancy" | "date" | "rank";
export const SearchGetRequestSortBy = {
    Relevancy: "relevancy",
    Date: "date",
    Rank: "rank",
} as const;
