/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchGetRequestClusteringVariable = "content" | "title" | "summary";

export const SearchGetRequestClusteringVariable = {
    Content: "content",
    Title: "title",
    Summary: "summary",
} as const;
