// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NewscatcherApi from "../../../index.js";

export declare namespace LatestHeadlinesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to retrieve latest headlines.
 */
export class LatestHeadlinesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LatestHeadlinesClient.Options>;

    constructor(options: LatestHeadlinesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves the latest headlines for the specified time period. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.GetLatestHeadlinesRequest} request
     * @param {LatestHeadlinesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.latestHeadlines.get({
     *         when: "7d",
     *         by_parse_date: true,
     *         lang: "en,es",
     *         not_lang: "fr,de",
     *         countries: "US,CA",
     *         not_countries: "UK,FR",
     *         predefined_sources: "top 50 US, top 20 GB",
     *         sources: "nytimes.com,finance.yahoo.com",
     *         not_sources: "cnn.com,wsj.com",
     *         not_author_name: "John Doe, Jane Doe",
     *         ranked_only: true,
     *         is_headline: true,
     *         is_opinion: true,
     *         is_paid_content: false,
     *         parent_url: "wsj.com/politics,wsj.com/tech",
     *         all_links: "https://aiindex.stanford.edu/report,https://www.stateof.ai",
     *         all_domain_links: "who.int,nih.gov",
     *         all_links_text: "Nvidia,Tesla",
     *         word_count_min: 300,
     *         word_count_max: 1000,
     *         page: 2,
     *         page_size: 50,
     *         clustering_enabled: true,
     *         clustering_threshold: 0.6,
     *         include_translation_fields: true,
     *         include_nlp_data: true,
     *         has_nlp: true,
     *         theme: "Finance,Tech",
     *         not_theme: "Crime,Sports",
     *         ORG_entity_name: "\"Apple Inc\" OR Microsoft",
     *         PER_entity_name: "\"Elon Musk\" OR \"Jeff Bezos\"",
     *         LOC_entity_name: "\"San Francisco\" OR \"New York City\"",
     *         MISC_entity_name: "AWS OR \"Microsoft Azure\"",
     *         title_sentiment_min: -0.5,
     *         title_sentiment_max: 0.5,
     *         content_sentiment_min: -0.5,
     *         content_sentiment_max: 0.5,
     *         iptc_tags: "20000199,20000209",
     *         not_iptc_tags: "20000205,20000209",
     *         iab_tags: "Business,Events",
     *         not_iab_tags: "Agriculture,Metals",
     *         custom_tags: "Tag1,Tag2",
     *         robots_compliant: true
     *     })
     */
    public get(
        request: NewscatcherApi.GetLatestHeadlinesRequest = {},
        requestOptions?: LatestHeadlinesClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.GetLatestHeadlinesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: NewscatcherApi.GetLatestHeadlinesRequest = {},
        requestOptions?: LatestHeadlinesClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.GetLatestHeadlinesResponse>> {
        const {
            when,
            by_parse_date: byParseDate,
            sort_by: sortBy,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            predefined_sources: predefinedSources,
            sources,
            not_sources: notSources,
            not_author_name: notAuthorName,
            ranked_only: rankedOnly,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            all_links_text: allLinksText,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            clustering_enabled: clusteringEnabled,
            clustering_variable: clusteringVariable,
            clustering_threshold: clusteringThreshold,
            include_translation_fields: includeTranslationFields,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ORG_entity_name: orgEntityName,
            PER_entity_name: perEntityName,
            LOC_entity_name: locEntityName,
            MISC_entity_name: miscEntityName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            iab_tags: iabTags,
            not_iab_tags: notIabTags,
            custom_tags: customTags,
            robots_compliant: robotsCompliant,
        } = request;
        const _queryParams: Record<string, unknown> = {
            when,
            by_parse_date: byParseDate,
            sort_by: sortBy != null ? sortBy : undefined,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            predefined_sources: predefinedSources,
            sources,
            not_sources: notSources,
            not_author_name: notAuthorName,
            ranked_only: rankedOnly,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            all_links_text: allLinksText,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            clustering_enabled: clusteringEnabled,
            clustering_variable: clusteringVariable != null ? clusteringVariable : undefined,
            clustering_threshold: clusteringThreshold,
            include_translation_fields: includeTranslationFields,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ORG_entity_name: orgEntityName,
            PER_entity_name: perEntityName,
            LOC_entity_name: locEntityName,
            MISC_entity_name: miscEntityName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            iab_tags: iabTags,
            not_iab_tags: notIabTags,
            custom_tags: customTags,
            robots_compliant: robotsCompliant,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/latest_headlines",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NewscatcherApi.GetLatestHeadlinesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/latest_headlines");
    }

    /**
     * Retrieves the latest headlines for the specified time period. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.PostLatestHeadlinesRequest} request
     * @param {LatestHeadlinesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.latestHeadlines.post({
     *         when: "7d",
     *         page_size: 1
     *     })
     */
    public post(
        request: NewscatcherApi.PostLatestHeadlinesRequest = {},
        requestOptions?: LatestHeadlinesClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.PostLatestHeadlinesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__post(request, requestOptions));
    }

    private async __post(
        request: NewscatcherApi.PostLatestHeadlinesRequest = {},
        requestOptions?: LatestHeadlinesClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.PostLatestHeadlinesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/latest_headlines",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NewscatcherApi.PostLatestHeadlinesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/latest_headlines");
    }
}
