/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as NewscatcherApi from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export declare namespace Latestheadlines {
    interface Options {
        environment?: core.Supplier<environments.NewscatcherApiEnvironment | string>;
        /** Override the x-api-token header */
        apiToken: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-api-token header */
        apiToken?: string;
    }
}

export class Latestheadlines {
    constructor(protected readonly _options: Latestheadlines.Options) {}

    /**
     * This endpoint allows you to get latest headlines. You need to specify since when you want to get the latest headlines. You can also filter by language, country, source, and more.
     *
     * @param {NewscatcherApi.LatestHeadlinesGetRequest} request
     * @param {Latestheadlines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     *
     * @example
     *     await client.latestheadlines.get({
     *         lang: "lang",
     *         notLang: "not_lang",
     *         countries: "countries",
     *         notCountries: "not_countries",
     *         sources: "sources",
     *         predefinedSources: "predefined_sources",
     *         notSources: "not_sources",
     *         notAuthorName: "not_author_name",
     *         parentUrl: "parent_url",
     *         allLinks: "all_links",
     *         allDomainLinks: "all_domain_links",
     *         iptcTags: "iptc_tags",
     *         notIptcTags: "not_iptc_tags",
     *         iabTags: "iab_tags",
     *         notIabTags: "not_iab_tags"
     *     })
     */
    public async get(
        request: NewscatcherApi.LatestHeadlinesGetRequest,
        requestOptions?: Latestheadlines.RequestOptions
    ): Promise<NewscatcherApi.LatestHeadlinesGetResponse> {
        const {
            when,
            byParseDate,
            sortBy,
            lang,
            notLang,
            countries,
            notCountries,
            sources,
            predefinedSources,
            notSources,
            notAuthorName,
            rankedOnly,
            isHeadline,
            isOpinion,
            isPaidContent,
            parentUrl,
            allLinks,
            allDomainLinks,
            wordCountMin,
            wordCountMax,
            page,
            pageSize,
            clusteringVariable,
            clusteringEnabled,
            clusteringThreshold,
            includeNlpData,
            hasNlp,
            theme,
            notTheme,
            orgEntityName,
            perEntityName,
            locEntityName,
            miscEntityName,
            titleSentimentMin,
            titleSentimentMax,
            contentSentimentMin,
            contentSentimentMax,
            iptcTags,
            notIptcTags,
            iabTags,
            notIabTags,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        if (when != null) {
            _queryParams["when"] = when;
        }

        if (byParseDate != null) {
            _queryParams["by_parse_date"] = byParseDate;
        }

        if (sortBy != null) {
            _queryParams["sort_by"] = sortBy;
        }

        _queryParams["lang"] = lang;
        _queryParams["not_lang"] = notLang;
        _queryParams["countries"] = countries;
        _queryParams["not_countries"] = notCountries;
        _queryParams["sources"] = sources;
        _queryParams["predefined_sources"] = predefinedSources;
        _queryParams["not_sources"] = notSources;
        _queryParams["not_author_name"] = notAuthorName;
        if (rankedOnly != null) {
            _queryParams["ranked_only"] = rankedOnly;
        }

        if (isHeadline != null) {
            _queryParams["is_headline"] = isHeadline;
        }

        if (isOpinion != null) {
            _queryParams["is_opinion"] = isOpinion;
        }

        if (isPaidContent != null) {
            _queryParams["is_paid_content"] = isPaidContent;
        }

        _queryParams["parent_url"] = parentUrl;
        _queryParams["all_links"] = allLinks;
        _queryParams["all_domain_links"] = allDomainLinks;
        if (wordCountMin != null) {
            _queryParams["word_count_min"] = wordCountMin;
        }

        if (wordCountMax != null) {
            _queryParams["word_count_max"] = wordCountMax;
        }

        if (page != null) {
            _queryParams["page"] = page;
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize;
        }

        if (clusteringVariable != null) {
            _queryParams["clustering_variable"] = clusteringVariable;
        }

        if (clusteringEnabled != null) {
            _queryParams["clustering_enabled"] = clusteringEnabled;
        }

        if (clusteringThreshold != null) {
            _queryParams["clustering_threshold"] = clusteringThreshold.toString();
        }

        if (includeNlpData != null) {
            _queryParams["include_nlp_data"] = includeNlpData.toString();
        }

        if (hasNlp != null) {
            _queryParams["has_nlp"] = hasNlp.toString();
        }

        if (theme != null) {
            _queryParams["theme"] = theme;
        }

        if (notTheme != null) {
            _queryParams["not_theme"] = notTheme;
        }

        if (orgEntityName != null) {
            _queryParams["ORG_entity_name"] = orgEntityName;
        }

        if (perEntityName != null) {
            _queryParams["PER_entity_name"] = perEntityName;
        }

        if (locEntityName != null) {
            _queryParams["LOC_entity_name"] = locEntityName;
        }

        if (miscEntityName != null) {
            _queryParams["MISC_entity_name"] = miscEntityName;
        }

        if (titleSentimentMin != null) {
            _queryParams["title_sentiment_min"] = titleSentimentMin.toString();
        }

        if (titleSentimentMax != null) {
            _queryParams["title_sentiment_max"] = titleSentimentMax.toString();
        }

        if (contentSentimentMin != null) {
            _queryParams["content_sentiment_min"] = contentSentimentMin.toString();
        }

        if (contentSentimentMax != null) {
            _queryParams["content_sentiment_max"] = contentSentimentMax.toString();
        }

        _queryParams["iptc_tags"] = iptcTags;
        _queryParams["not_iptc_tags"] = notIptcTags;
        _queryParams["iab_tags"] = iabTags;
        _queryParams["not_iab_tags"] = notIabTags;
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.NewscatcherApiEnvironment.Default,
                "api/latest_headlines"
            ),
            method: "GET",
            headers: {
                "x-api-token": await core.Supplier.get(this._options.apiToken),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "newscatcher-sdk/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.LatestHeadlinesGetResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError();
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * This endpoint allows you to get latest headlines. You need to specify since when you want to get the latest headlines. You can also filter by language, country, source, and more.
     *
     * @param {NewscatcherApi.LatestHeadlinesRequest} request
     * @param {Latestheadlines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     *
     * @example
     *     await client.latestheadlines.post()
     */
    public async post(
        request: NewscatcherApi.LatestHeadlinesRequest = {},
        requestOptions?: Latestheadlines.RequestOptions
    ): Promise<NewscatcherApi.LatestHeadlinesPostResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.NewscatcherApiEnvironment.Default,
                "api/latest_headlines"
            ),
            method: "POST",
            headers: {
                "x-api-token": await core.Supplier.get(this._options.apiToken),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "newscatcher-sdk/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.LatestHeadlinesRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.LatestHeadlinesPostResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError();
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
