/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../../../../index";

/**
 * @example
 *     {
 *         ids: ["8ea8a784568ffaa05cb6d1ab2d2e84dd", "0146a551ef05ab1c494a55e806e3ce64"],
 *         links: ["https://www.nytimes.com/2024/08/30/technology/ai-chatbot-chatgpt-manipulation.html", "https://www.bbc.com/news/articles/c39k379grzlo"]
 *     }
 */
export interface SearchUrlPostRequest {
    ids?: NewscatcherApi.Ids;
    links?: NewscatcherApi.Links;
    /**
     * The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
     *
     * Formats with examples:
     * - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
     * - YYYY-MM-dd: `2024-07-01`
     * - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
     * - YYYY/mm/dd: `2024/07/01`
     * - English phrases: `1 day ago`, `today`
     *
     */
    from?: NewscatcherApi.From;
    /**
     * The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
     *
     * Formats with examples:
     * - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
     * - YYYY-MM-dd: `2024-07-01`
     * - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
     * - YYYY/mm/dd: `2024/07/01`
     * - English phrases: `1 day ago`, `today`
     *
     */
    to?: NewscatcherApi.To;
    page?: NewscatcherApi.Page;
    pageSize?: NewscatcherApi.PageSize;
}
