// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as NewscatcherApi from "../../../index.js";

export declare namespace SearchClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to search for articles.
 */
export class SearchClient {
    protected readonly _options: SearchClient.Options;

    constructor(options: SearchClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Searches for articles based on specified criteria such as keyword, language, country, source, and more.
     *
     * @param {NewscatcherApi.SearchGetRequest} request
     * @param {SearchClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.search.get({
     *         q: "\"supply chain\" AND Amazon NOT China",
     *         search_in: "title_content, title_content_translated",
     *         include_translation_fields: true,
     *         predefined_sources: "top 100 US, top 5 GB",
     *         source_name: "sport",
     *         sources: "nytimes.com",
     *         not_sources: "cnn.com",
     *         lang: "en",
     *         not_lang: "fr",
     *         countries: "US",
     *         not_countries: "UK",
     *         not_author_name: "John Doe",
     *         from_: "2024-07-01T00:00:00Z",
     *         to_: "2024-07-01T00:00:00Z",
     *         parent_url: "https://www.washingtonpost.com/politics",
     *         all_links: "https://aiindex.stanford.edu/report",
     *         all_domain_links: "nvidia.com",
     *         news_type: "General News Outlets",
     *         include_nlp_data: true,
     *         has_nlp: true,
     *         theme: "Business,Finance",
     *         not_theme: "Crime",
     *         ORG_entity_name: "Apple",
     *         PER_entity_name: "Elon Musk",
     *         LOC_entity_name: "California",
     *         MISC_entity_name: "Bitcoin",
     *         iptc_tags: "20000199,20000209",
     *         not_iptc_tags: "20000205,20000209",
     *         iab_tags: "Business,Events",
     *         not_iab_tags: "Agriculture,Metals",
     *         custom_tags: "Tag1,Tag2,Tag3"
     *     })
     */
    public get(
        request: NewscatcherApi.SearchGetRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: NewscatcherApi.SearchGetRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchGetResponse>> {
        const {
            q,
            search_in: searchIn,
            include_translation_fields: includeTranslationFields,
            predefined_sources: predefinedSources,
            source_name: sourceName,
            sources,
            not_sources: notSources,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            not_author_name: notAuthorName,
            from_,
            to_: to,
            published_date_precision: publishedDatePrecision,
            by_parse_date: byParseDate,
            sort_by: sortBy,
            ranked_only: rankedOnly,
            from_rank: fromRank,
            to_rank: toRank,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            additional_domain_info: additionalDomainInfo,
            is_news_domain: isNewsDomain,
            news_domain_type: newsDomainType,
            news_type: newsType,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            clustering_enabled: clusteringEnabled,
            clustering_variable: clusteringVariable,
            clustering_threshold: clusteringThreshold,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ORG_entity_name: orgEntityName,
            PER_entity_name: perEntityName,
            LOC_entity_name: locEntityName,
            MISC_entity_name: miscEntityName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            iab_tags: iabTags,
            not_iab_tags: notIabTags,
            custom_tags: customTags,
            exclude_duplicates: excludeDuplicates,
            robots_compliant: robotsCompliant,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.q = q;
        if (searchIn != null) {
            _queryParams.search_in = searchIn;
        }

        if (includeTranslationFields != null) {
            _queryParams.include_translation_fields = includeTranslationFields.toString();
        }

        if (predefinedSources != null) {
            _queryParams.predefined_sources = predefinedSources;
        }

        if (sourceName != null) {
            _queryParams.source_name = sourceName;
        }

        if (sources != null) {
            _queryParams.sources = sources;
        }

        if (notSources != null) {
            _queryParams.not_sources = notSources;
        }

        if (lang != null) {
            _queryParams.lang = lang;
        }

        if (notLang != null) {
            _queryParams.not_lang = notLang;
        }

        if (countries != null) {
            _queryParams.countries = countries;
        }

        if (notCountries != null) {
            _queryParams.not_countries = notCountries;
        }

        if (notAuthorName != null) {
            _queryParams.not_author_name = notAuthorName;
        }

        if (from_ != null) {
            _queryParams.from_ = typeof from_ === "string" ? from_ : toJson(from_);
        }

        if (to != null) {
            _queryParams.to_ = typeof to === "string" ? to : toJson(to);
        }

        if (publishedDatePrecision != null) {
            _queryParams.published_date_precision = publishedDatePrecision;
        }

        if (byParseDate != null) {
            _queryParams.by_parse_date = byParseDate.toString();
        }

        if (sortBy != null) {
            _queryParams.sort_by = sortBy;
        }

        if (rankedOnly != null) {
            _queryParams.ranked_only = rankedOnly.toString();
        }

        if (fromRank != null) {
            _queryParams.from_rank = fromRank.toString();
        }

        if (toRank != null) {
            _queryParams.to_rank = toRank.toString();
        }

        if (isHeadline != null) {
            _queryParams.is_headline = isHeadline.toString();
        }

        if (isOpinion != null) {
            _queryParams.is_opinion = isOpinion.toString();
        }

        if (isPaidContent != null) {
            _queryParams.is_paid_content = isPaidContent.toString();
        }

        if (parentUrl != null) {
            _queryParams.parent_url = parentUrl;
        }

        if (allLinks != null) {
            _queryParams.all_links = allLinks;
        }

        if (allDomainLinks != null) {
            _queryParams.all_domain_links = allDomainLinks;
        }

        if (additionalDomainInfo != null) {
            _queryParams.additional_domain_info = additionalDomainInfo.toString();
        }

        if (isNewsDomain != null) {
            _queryParams.is_news_domain = isNewsDomain.toString();
        }

        if (newsDomainType != null) {
            _queryParams.news_domain_type = newsDomainType;
        }

        if (newsType != null) {
            _queryParams.news_type = newsType;
        }

        if (wordCountMin != null) {
            _queryParams.word_count_min = wordCountMin.toString();
        }

        if (wordCountMax != null) {
            _queryParams.word_count_max = wordCountMax.toString();
        }

        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (clusteringEnabled != null) {
            _queryParams.clustering_enabled = clusteringEnabled.toString();
        }

        if (clusteringVariable != null) {
            _queryParams.clustering_variable = clusteringVariable;
        }

        if (clusteringThreshold != null) {
            _queryParams.clustering_threshold = clusteringThreshold.toString();
        }

        if (includeNlpData != null) {
            _queryParams.include_nlp_data = includeNlpData.toString();
        }

        if (hasNlp != null) {
            _queryParams.has_nlp = hasNlp.toString();
        }

        if (theme != null) {
            _queryParams.theme = theme;
        }

        if (notTheme != null) {
            _queryParams.not_theme = notTheme;
        }

        if (orgEntityName != null) {
            _queryParams.ORG_entity_name = orgEntityName;
        }

        if (perEntityName != null) {
            _queryParams.PER_entity_name = perEntityName;
        }

        if (locEntityName != null) {
            _queryParams.LOC_entity_name = locEntityName;
        }

        if (miscEntityName != null) {
            _queryParams.MISC_entity_name = miscEntityName;
        }

        if (titleSentimentMin != null) {
            _queryParams.title_sentiment_min = titleSentimentMin.toString();
        }

        if (titleSentimentMax != null) {
            _queryParams.title_sentiment_max = titleSentimentMax.toString();
        }

        if (contentSentimentMin != null) {
            _queryParams.content_sentiment_min = contentSentimentMin.toString();
        }

        if (contentSentimentMax != null) {
            _queryParams.content_sentiment_max = contentSentimentMax.toString();
        }

        if (iptcTags != null) {
            _queryParams.iptc_tags = iptcTags;
        }

        if (notIptcTags != null) {
            _queryParams.not_iptc_tags = notIptcTags;
        }

        if (iabTags != null) {
            _queryParams.iab_tags = iabTags;
        }

        if (notIabTags != null) {
            _queryParams.not_iab_tags = notIabTags;
        }

        if (customTags != null) {
            _queryParams.custom_tags = customTags;
        }

        if (excludeDuplicates != null) {
            _queryParams.exclude_duplicates = excludeDuplicates.toString();
        }

        if (robotsCompliant != null) {
            _queryParams.robots_compliant = robotsCompliant.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NewscatcherApi.SearchGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling GET /api/search.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Searches for articles based on specified criteria such as keyword, language, country, source, and more.
     *
     * @param {NewscatcherApi.SearchPostRequest} request
     * @param {SearchClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.search.post({
     *         q: "\"supply chain\" AND Amazon NOT China",
     *         page_size: 1
     *     })
     */
    public post(
        request: NewscatcherApi.SearchPostRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__post(request, requestOptions));
    }

    private async __post(
        request: NewscatcherApi.SearchPostRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchPostResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NewscatcherApi.SearchPostResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling POST /api/search.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-token": apiKeyValue };
    }
}
