// This file was auto-generated by Fern from our API Definition.

export const SourcesGetRequestNewsDomainType = {
    OriginalContent: "Original Content",
    Aggregator: "Aggregator",
    PressReleases: "Press Releases",
    Republisher: "Republisher",
    Other: "Other",
} as const;
export type SourcesGetRequestNewsDomainType =
    (typeof SourcesGetRequestNewsDomainType)[keyof typeof SourcesGetRequestNewsDomainType];
