/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * AdditionalSourceInfo DTO class.
 */
export interface AdditionalSourceInfo {
    nbArticlesFor7D?: number;
    country?: string;
    rank?: number;
    isNewsDomain?: boolean;
    newsDomainType?: string;
    newsType?: string;
}
