// This file was auto-generated by Fern from our API Definition.

/**
 * Additional information about the domain of the article.
 */
export interface AdditionalDomainInfoEntity {
    /** Indicates whether the domain is a news domain. */
    is_news_domain?: boolean | undefined;
    /** The type of news content provided by the domain. */
    news_type?: string | undefined;
    /** The type of news domain. */
    news_domain_type?: string | undefined;
}
