// This file was auto-generated by Fern from our API Definition.

/**
 * The data model for additional information about a news source.
 */
export interface AdditionalSourceInfo {
    /** The number of articles published by the source in the last seven days. */
    nb_articles_for_7d?: number;
    /** The country of origin of the news source. */
    country?: string;
    /** The SEO rank of the news source. */
    rank?: number;
    /** Indicates whether the source is a news domain. */
    is_news_domain?: boolean;
    /** The type of news domain. */
    news_domain_type?: string;
    /** The category of news provided by the source. */
    news_type?: string;
}
