// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../index.js";

/**
 * The response model for a successful `Aggregation count` request. Response field behavior:
 * - Required fields are guaranteed to be present and non-null.
 * - Optional fields may be `null` or `undefined` if the data point is not presented or couldn't be extracted during processing.
 */
export interface AggregationCountResponseDto extends NewscatcherApi.BaseSearchResponseDto {
    /** The aggregation results. Can be either a dictionary or a list of dictionaries. */
    aggregations?: AggregationCountResponseDto.Aggregations;
    user_input?: NewscatcherApi.UserInputDto;
}

export namespace AggregationCountResponseDto {
    /**
     * The aggregation results. Can be either a dictionary or a list of dictionaries.
     */
    export type Aggregations = NewscatcherApi.AggregationItem | NewscatcherApi.AggregationItem[];
}
