// This file was auto-generated by Fern from our API Definition.

/**
 * The domain(s) mentioned in the article. For multiple domains, use a comma-separated string or an array of strings.
 *
 * For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
 */
export type AllDomainLinks = string | string[];
