// This file was auto-generated by Fern from our API Definition.

/**
 * Detailed information about a link found in an article.
 */
export interface AllLinksDataItem {
    /** The domain of the linked URL. */
    domain_url: string;
    /** The complete URL of the link. */
    link: string;
    /** The anchor text of the link. */
    text: string;
}
