/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string or an array of strings.
 *
 * Examples:
 * - `"https://aiindex.stanford.edu/report/, https://www.stateof.ai/"`
 * - `["https://aiindex.stanford.edu/report/", "https://www.stateof.ai/"]`
 *
 * For more details, see [Search by URL](/docs/v3/documentation/how-to/search-by-url).
 */
export type AllLinks = string | string[];
