// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../index.js";

/**
 * A list of articles matching the search criteria.
 */
export type ArticlesDto = NewscatcherApi.ArticleEntity[];
