// This file was auto-generated by Fern from our API Definition.

/**
 * The base response model containing common fields for search operations.
 */
export interface BaseSearchResponseDto {
    /** The status of the response. */
    status?: string;
    /** The total number of articles matching the search criteria. */
    total_hits?: number;
    /** The current page number of the results. */
    page?: number;
    /** The total number of pages available for the given search criteria. */
    total_pages?: number;
    /** The number of articles per page. */
    page_size?: number;
}
