// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../index.js";

/**
 * The data model representing a single article in the `Breaking news` search results.
 */
export interface BreakingNewsArticleEntity {
    /** The title of the article. */
    title: string;
    /** The primary author of the article. */
    author?: string;
    /** A list of authors of the article. */
    authors?: BreakingNewsArticleEntity.Authors;
    /** A list of journalists associated with the article. */
    journalists?: BreakingNewsArticleEntity.Journalists;
    /** The date the article was published. */
    published_date?: string;
    /** The precision of the published date. */
    published_date_precision?: string;
    /** The date the article was last updated. */
    updated_date?: string;
    /** The precision of the updated date. */
    updated_date_precision?: string;
    /** The date the article was parsed. */
    parse_date?: string;
    /** The URL link to the article. */
    link: string;
    /** The domain URL of the article. */
    domain_url: string;
    /** The full domain URL of the article. */
    full_domain_url: string;
    /** The name of the source where the article was published. */
    name_source?: string;
    /** Indicates if the article is a headline. */
    is_headline?: boolean;
    /** Indicates if the article is paid content. */
    paid_content?: boolean;
    /** The categorical URL of the article. */
    parent_url: string;
    /** The country where the article was published. */
    country?: string;
    /** The rights information for the article. */
    rights?: string;
    /** The rank of the article's source. */
    rank: number;
    /** The media associated with the article. */
    media?: string;
    /** The language in which the article is written. */
    language?: string;
    /** A brief description of the article. */
    description?: string;
    /** The content of the article. */
    content: string;
    /** The word count of the article. */
    word_count?: number;
    /** Indicates if the article is an opinion piece. */
    is_opinion?: boolean;
    /** The Twitter account associated with the article. */
    twitter_account?: string;
    /** A list of all URLs mentioned in the article. */
    all_links?: BreakingNewsArticleEntity.AllLinks;
    /** A list of all domain URLs mentioned in the article. */
    all_domain_links?: BreakingNewsArticleEntity.AllDomainLinks;
    nlp?: NewscatcherApi.NlpDataEntity;
    /** The unique identifier for the article. */
    id: string;
    /** The relevance score of the article. */
    score: number;
    /** True if the article content can be safely accessed according to the publisher's robots.txt rules; false otherwise. */
    robots_compliant?: boolean;
}

export namespace BreakingNewsArticleEntity {
    /**
     * A list of authors of the article.
     */
    export type Authors = string[] | string;
    /**
     * A list of journalists associated with the article.
     */
    export type Journalists = string[] | string;
    /**
     * A list of all URLs mentioned in the article.
     */
    export type AllLinks = string[] | string;
    /**
     * A list of all domain URLs mentioned in the article.
     */
    export type AllDomainLinks = string[] | string;
}
