/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * The data model representing a breaking news event with its associated articles.
 */
export interface BreakingNewsEventEntity {
    /** Unique identifier for the breaking news event/cluster. */
    eventId: string;
    /** Number of articles in this breaking news cluster. */
    articlesCount: number;
    /** The articles associated with this breaking news event. */
    articles: NewscatcherApi.BreakingNewsArticleEntity[];
}
