/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * The response model for the breaking news requests. Response field behavior:
 * - Required fields are guaranteed to be present and non-null.
 * - Optional fields may be `null` or `undefined` if the data point is not presented or couldn't be extracted during processing.
 * - To access article properties in the `articles` response array, use array index notation. For example, `articles[n].title`, where `n` is the zero-based index of the article object (0, 1, 2, etc.).
 * - The `nlp` property within the article object `articles[n].nlp` is only available with NLP-enabled subscription plans.
 */
export interface BreakingNewsResponseDto extends NewscatcherApi.BaseSearchResponseDto {
    /** A list of breaking news events, each containing relevant articles. */
    breakingNewsEvents?: NewscatcherApi.BreakingNewsEventEntity[];
    userInput?: NewscatcherApi.UserInputDto;
}
