/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A list of all domain URLs mentioned in the article.
 */
export type BreakingNewsArticleEntityAllDomainLinks = string[] | string;
