// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../index.js";

/**
 * The data model representing a breaking news event with its associated articles.
 */
export interface BreakingNewsEventEntity {
    /** Unique identifier for the breaking news event/cluster. */
    event_id: string;
    /** Number of articles in this breaking news cluster. */
    articles_count: number;
    /** The articles associated with this breaking news event. */
    articles: NewscatcherApi.BreakingNewsArticleEntity[];
}
