/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If true, the `from_` and `to_` parameters use article parse dates instead of published dates. Additionally, the `parse_date` variable is added to the output for each article object.
 */
export type ByParseDate = boolean;
