/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * The data model representing a single cluster of articles.
 */
export interface ClusterEntity {
    /** The unique identifier for the cluster. */
    clusterId: string;
    /** The number of articles in the cluster. */
    clusterSize: number;
    /** A list of articles in the cluster. */
    articles: NewscatcherApi.ArticleEntity[];
}
