// This file was auto-generated by Fern from our API Definition.

/**
 * Determines whether to group similar articles into clusters. If true, the API returns clustered results.
 *
 * To learn more, see [Clustering news articles](/docs/v3/documentation/guides-and-concepts/clustering-news-articles).
 */
export type ClusteringEnabled = boolean;
