// This file was auto-generated by Fern from our API Definition.

/**
 * **Deprecated from January 1, 2026 onward.** For articles published on or after 2026-01-01, this parameter is ignored. Clustering always uses a combined `title + content` embedding generated by the Qwen3-Embedding-0.6B model, regardless of the value supplied.
 *
 * For articles published before 2026-01-01, this parameter remains functional and specifies which part of the article to use for clustering:
 * - `content`: Uses the full article content (default).
 * - `title`: Uses only the article title.
 * - `summary`: Uses the article summary.
 *
 * To learn more, see [Clustering news articles](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/clustering-news-articles).
 */
export const ClusteringVariable = {
    Content: "content",
    Title: "title",
    Summary: "summary",
} as const;
export type ClusteringVariable = (typeof ClusteringVariable)[keyof typeof ClusteringVariable];
