/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cluster DTO class.
 */
export interface Cluster {
    clusterId: string;
    clusterSize: number;
    articles: Record<string, unknown>[];
}
