// This file was auto-generated by Fern from our API Definition.

/**
 * Filters articles based on the minimum sentiment score of their content.
 *
 * Range is `-1.0` to `1.0`, where:
 * - Negative values indicate negative sentiment.
 * - Positive values indicate positive sentiment.
 * - Values close to 0 indicate neutral sentiment.
 *
 * To learn more, see [NLP features](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/nlp-features).
 */
export type ContentSentimentMin = number;
