/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * The response model for a failed `Authors` search request.
 */
export interface FailedAuthorsResponseDto extends NewscatcherApi.BaseSearchResponseDto {
    /** An empty list of articles, as no matches were found. */
    articles?: Record<string, unknown>[];
    userInput?: NewscatcherApi.UserInputDto;
}
