// This file was auto-generated by Fern from our API Definition.

/**
 * If true, filters results to include only articles that have NLP data.
 *
 * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
 */
export type HasNlp = boolean;
