/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If true, includes an NLP object for each article in the response. This object provides results of NLP analysis, including article theme, summary, sentiment, tags, and named entity recognition if available.
 *
 * **Note**: NLP coverage and analysis completeness may vary by language, with full data available for articles in English and Arabic. The `include_nlp_data` parameter is available only in NLP subscription plans.
 *
 * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
 */
export type IncludeNlpData = boolean;
