/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If true, the response includes translation fields `title_translated_en` and `content_translated_en`.
 *
 * **Note**: Article translations are available only in the NLP plan.
 */
export type IncludeTranslationFields = boolean;
