// This file was auto-generated by Fern from our API Definition.

/**
 * If true, includes an NLP object for each article in the response. This object provides results of NLP analysis, including article theme, summary, sentiment, tags, and named entity recognition if available.
 *
 * To learn more, see [NLP features](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/nlp-features).
 */
export type IncludeNlpData = boolean;
