/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If true, only returns articles that were posted on the home page of a given news domain.
 */
export type IsHeadline = boolean;
