/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If false, returns only articles that have publicly available complete content. Some publishers partially block content, so this setting ensures that only full articles are retrieved.
 */
export type IsPaidContent = boolean;
