// This file was auto-generated by Fern from our API Definition.

/**
 * Filters articles that mention other named entities not falling under person, organization, or location categories. Includes events, nationalities, products, works of art, and more.
 *
 * - To specify multiple entities, use `AND`, `OR`, `NOT` operators, and `\"` escape literals for exact matches.
 * - To search in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
 *
 * To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
 */
export type MiscEntityName = string;
