/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * A list of named entities identified in the article.
 */
export type NamedEntityList = NewscatcherApi.NamedEntityListItem[];
