/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Filters results based on the news type. Multiple types can be specified using a comma-separated string or an array of strings.
 *
 * Examples:
 * - `"General News Outlets,Tech News and Updates"`
 * - `["General News Outlets", "Tech News and Updates"]`
 *
 * For a complete list of available news types, see [Enumerated parameters > News type](/docs/v3/api-reference/overview/enumerated-parameters#news-type-news-type).
 */
export type NewsType = string | string[];
