/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Inverse of the `iab_tags` parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string or an array of strings.
 *
 * Examples:
 * - `"Agriculture, Metals"`
 * - `["Agriculture", "Metals"]`
 *
 * **Note**: The `not_iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
 *
 * To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
 */
export type NotIabTags = string | string[];
