// This file was auto-generated by Fern from our API Definition.

/**
 * Inverse of the `theme` parameter. Excludes articles based on their general topic, as determined by NLP analysis. To exclude multiple themes, use a comma-separated string or an array of strings.
 *
 * Examples:
 * - `"Crime, Tech"`
 * - `["Crime", "Tech"]`
 *
 * **Note**: The `not_theme` parameter is only available if NLP is included in your subscription plan.
 *
 * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
 */
export type NotTheme = string | string[];
