// This file was auto-generated by Fern from our API Definition.

/**
 * The keyword(s) to search for in articles. Query syntax supports logical operators (`AND`, `OR`, `NOT`) and wildcards:
 *
 * - For exact phrases, use escaped quotes: `\"technology news\"`
 * - Use `*` for wildcards: `technolog*` (cannot start with `*`)
 * - Use `+` to include and `-` to exclude: `+Apple`, `-Google`
 * - Boolean operators: `technology AND (Apple OR Microsoft) NOT Google`
 * - Forbidden characters: `[` `]` `/` `\\` `:` `^` and URL-encoded equivalents
 *
 * **Note:** The API automatically inserts `AND` operators between standalone terms, so strings like `"machine learning"` become `"machine AND learning"`. To avoid syntax errors (especially in queries with `OR` operators), use literal escape `"\"machine learning\""`.
 *
 * For detailed syntax rules, see [Advanced querying](/docs/v3/documentation/guides-and-concepts/advanced-querying).
 */
export type Q = string;
