/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The keyword(s) to search for in articles. Query syntax supports logical operators (`AND`, `OR`, `NOT`) and wildcards:
 *
 * - For an exact match, use double quotes. For example, `"technology news"`.
 * - Use `*` to search for any keyword.
 * - Use `+` to include and `-` to exclude specific words or phrases. For example, `+Apple`, `-Google`.
 * - Use `AND`, `OR`, and `NOT` to refine search results. For example, `technology AND (Apple OR Microsoft) NOT Google`.
 *
 * For more details, see [Advanced querying](/docs/v3/documentation/guides-and-concepts/advanced-querying).
 */
export type Q = string;
