// This file was auto-generated by Fern from our API Definition.

/**
 * Sentiment scores for the article's title and content.
 */
export interface SentimentScores {
    /** The sentiment score for the article title (-1.0 to 1.0). */
    title?: number;
    /** The sentiment score for the article content (-1.0 to 1.0). */
    content?: number;
}
