/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SimilarDocument DTO class.
 */
export interface SimilarDocument {
    id: string;
    score: number;
    title: string;
    link: string;
}
