/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

/**
 * The data model for information about a news source.
 */
export interface SourceInfo {
    /** The name of the news source. */
    nameSource?: string;
    /** The domain URL of the news source. */
    domainUrl: string;
    /** The logo of the news source. */
    logo?: string;
    additionalInfo?: NewscatcherApi.AdditionalSourceInfo;
}
