// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../index.js";

/**
 * The data model for information about a news source.
 */
export interface SourceInfo {
    /** The name of the news source. */
    name_source?: string;
    /** The domain URL of the news source. */
    domain_url: string;
    /** The logo of the news source. */
    logo?: string;
    additional_info?: NewscatcherApi.AdditionalSourceInfo;
}
