// This file was auto-generated by Fern from our API Definition.

/**
 * Filters articles based on their general topic, as determined by NLP analysis. To select multiple themes, use a comma-separated string or an array of strings.
 *
 * Examples:
 * - `"Finance, Tech"`
 * - `["Finance", "Tech"]`
 *
 * **Note**: The `theme` parameter is only available if NLP is included in your subscription plan.
 *
 * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
 *
 * Available options: `Business`, `Economics`, `Entertainment`, `Finance`, `Health`, `Politics`, `Science`, `Sports`, `Tech`, `Crime`, `Financial Crime`, `Lifestyle`, `Automotive`, `Travel`, `Weather`, `General`.
 */
export type Theme = string | string[];
