// This file was auto-generated by Fern from our API Definition.

/**
 * Represents the article count for a specific time frame.
 */
export interface TimeFrameCount {
    /** The timestamp for the aggregation period in format "YYYY-MM-DD HH:mm:ss" */
    time_frame: string;
    /** The number of articles published during this time frame */
    article_count: number;
}
