// This file was auto-generated by Fern from our API Definition.

/**
 * Filters articles based on the maximum sentiment score of their titles.
 *
 * Range is `-1.0` to `1.0`, where:
 * - Negative values indicate negative sentiment.
 * - Positive values indicate positive sentiment.
 * - Values close to 0 indicate neutral sentiment.
 *
 * **Note**: The `title_sentiment_max` parameter is only available if NLP is included in your subscription plan.
 *
 * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
 */
export type TitleSentimentMax = number;
