/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../index";

export interface ValidationError {
    loc: NewscatcherApi.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
