/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The time period for which you want to get the latest headlines.
 *
 * Format examples:
 * - `7d`: Last seven days
 * - `30d`: Last 30 days
 * - `1h`: Last hour
 * - `24h`: Last 24 hours
 */
export type When = string;
