/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NewscatcherApi from "../../../../index";

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface MoreLikeThisRequest {
    q: string;
    searchIn?: string;
    includeSimilarDocuments?: boolean;
    similarDocumentsNumber?: number;
    similarDocumentsFields?: string;
    predefinedSources?: unknown;
    sources?: unknown;
    notSources?: unknown;
    lang?: unknown;
    notLang?: unknown;
    countries?: unknown;
    notCountries?: unknown;
    from?: NewscatcherApi.MoreLikeThisRequestFrom;
    to?: NewscatcherApi.MoreLikeThisRequestTo;
    byParseDate?: boolean;
    publishedDatePrecision?: string;
    sortBy?: string;
    rankedOnly?: NewscatcherApi.MoreLikeThisRequestRankedOnly;
    fromRank?: number;
    toRank?: number;
    isHeadline?: boolean;
    isOpinion?: boolean;
    isPaidContent?: boolean;
    parentUrl?: unknown;
    allLinks?: unknown;
    allDomainLinks?: unknown;
    wordCountMin?: number;
    wordCountMax?: number;
    page?: number;
    pageSize?: number;
    includeNlpData?: boolean;
    hasNlp?: boolean;
    theme?: string;
    notTheme?: string;
    titleSentimentMin?: number;
    titleSentimentMax?: number;
    contentSentimentMin?: number;
    contentSentimentMax?: number;
    iptcTags?: unknown;
    notIptcTags?: unknown;
}
