// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NewscatcherApi from "../../../index.js";

export declare namespace AuthorsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to search by author.
 */
export class AuthorsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AuthorsClient.Options>;

    constructor(options: AuthorsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Searches for articles written by a specified author. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.AuthorsGetRequest} request
     * @param {AuthorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.authors.get({
     *         author_name: "Jane Smith",
     *         not_author_name: "John Doe",
     *         predefined_sources: "top 100 US, top 5 GB",
     *         sources: "nytimes.com",
     *         not_sources: "cnn.com",
     *         lang: "en",
     *         not_lang: "fr",
     *         countries: "US",
     *         not_countries: "UK",
     *         from_: "2024-07-01T00:00:00Z",
     *         to_: "2024-07-01T00:00:00Z",
     *         parent_url: "https://www.washingtonpost.com/politics",
     *         all_links: "https://aiindex.stanford.edu/report",
     *         all_domain_links: "nvidia.com",
     *         include_translation_fields: true,
     *         include_nlp_data: true,
     *         has_nlp: true,
     *         theme: "Business,Finance",
     *         not_theme: "Crime",
     *         ner_name: "Tesla",
     *         iptc_tags: "20000199,20000209",
     *         not_iptc_tags: "20000205,20000209",
     *         iab_tags: "Business,Events",
     *         not_iab_tags: "Agriculture,Metals",
     *         custom_tags: "Tag1,Tag2,Tag3"
     *     })
     */
    public get(
        request: NewscatcherApi.AuthorsGetRequest,
        requestOptions?: AuthorsClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.AuthorsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: NewscatcherApi.AuthorsGetRequest,
        requestOptions?: AuthorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.AuthorsGetResponse>> {
        const {
            author_name: authorName,
            not_author_name: notAuthorName,
            predefined_sources: predefinedSources,
            sources,
            not_sources: notSources,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            from_,
            to_: to,
            published_date_precision: publishedDatePrecision,
            by_parse_date: byParseDate,
            sort_by: sortBy,
            ranked_only: rankedOnly,
            from_rank: fromRank,
            to_rank: toRank,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            include_translation_fields: includeTranslationFields,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ner_name: nerName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            iab_tags: iabTags,
            not_iab_tags: notIabTags,
            custom_tags: customTags,
            robots_compliant: robotsCompliant,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.author_name = authorName;
        if (notAuthorName != null) {
            _queryParams.not_author_name = notAuthorName;
        }

        if (predefinedSources != null) {
            _queryParams.predefined_sources = predefinedSources;
        }

        if (sources != null) {
            _queryParams.sources = sources;
        }

        if (notSources != null) {
            _queryParams.not_sources = notSources;
        }

        if (lang != null) {
            _queryParams.lang = lang;
        }

        if (notLang != null) {
            _queryParams.not_lang = notLang;
        }

        if (countries != null) {
            _queryParams.countries = countries;
        }

        if (notCountries != null) {
            _queryParams.not_countries = notCountries;
        }

        if (from_ != null) {
            _queryParams.from_ = typeof from_ === "string" ? from_ : toJson(from_);
        }

        if (to != null) {
            _queryParams.to_ = typeof to === "string" ? to : toJson(to);
        }

        if (publishedDatePrecision != null) {
            _queryParams.published_date_precision = publishedDatePrecision;
        }

        if (byParseDate != null) {
            _queryParams.by_parse_date = byParseDate.toString();
        }

        if (sortBy != null) {
            _queryParams.sort_by = sortBy;
        }

        if (rankedOnly != null) {
            _queryParams.ranked_only = rankedOnly.toString();
        }

        if (fromRank != null) {
            _queryParams.from_rank = fromRank.toString();
        }

        if (toRank != null) {
            _queryParams.to_rank = toRank.toString();
        }

        if (isHeadline != null) {
            _queryParams.is_headline = isHeadline.toString();
        }

        if (isOpinion != null) {
            _queryParams.is_opinion = isOpinion.toString();
        }

        if (isPaidContent != null) {
            _queryParams.is_paid_content = isPaidContent.toString();
        }

        if (parentUrl != null) {
            _queryParams.parent_url = parentUrl;
        }

        if (allLinks != null) {
            _queryParams.all_links = allLinks;
        }

        if (allDomainLinks != null) {
            _queryParams.all_domain_links = allDomainLinks;
        }

        if (wordCountMin != null) {
            _queryParams.word_count_min = wordCountMin.toString();
        }

        if (wordCountMax != null) {
            _queryParams.word_count_max = wordCountMax.toString();
        }

        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (includeTranslationFields != null) {
            _queryParams.include_translation_fields = includeTranslationFields.toString();
        }

        if (includeNlpData != null) {
            _queryParams.include_nlp_data = includeNlpData.toString();
        }

        if (hasNlp != null) {
            _queryParams.has_nlp = hasNlp.toString();
        }

        if (theme != null) {
            _queryParams.theme = theme;
        }

        if (notTheme != null) {
            _queryParams.not_theme = notTheme;
        }

        if (nerName != null) {
            _queryParams.ner_name = nerName;
        }

        if (titleSentimentMin != null) {
            _queryParams.title_sentiment_min = titleSentimentMin.toString();
        }

        if (titleSentimentMax != null) {
            _queryParams.title_sentiment_max = titleSentimentMax.toString();
        }

        if (contentSentimentMin != null) {
            _queryParams.content_sentiment_min = contentSentimentMin.toString();
        }

        if (contentSentimentMax != null) {
            _queryParams.content_sentiment_max = contentSentimentMax.toString();
        }

        if (iptcTags != null) {
            _queryParams.iptc_tags = iptcTags;
        }

        if (notIptcTags != null) {
            _queryParams.not_iptc_tags = notIptcTags;
        }

        if (iabTags != null) {
            _queryParams.iab_tags = iabTags;
        }

        if (notIabTags != null) {
            _queryParams.not_iab_tags = notIabTags;
        }

        if (customTags != null) {
            _queryParams.custom_tags = customTags;
        }

        if (robotsCompliant != null) {
            _queryParams.robots_compliant = robotsCompliant.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/authors",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NewscatcherApi.AuthorsGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/authors");
    }

    /**
     * Searches for articles by author. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.AuthorsPostRequest} request
     * @param {AuthorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.authors.post({
     *         author_name: "David Muir"
     *     })
     */
    public post(
        request: NewscatcherApi.AuthorsPostRequest,
        requestOptions?: AuthorsClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.AuthorsPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__post(request, requestOptions));
    }

    private async __post(
        request: NewscatcherApi.AuthorsPostRequest,
        requestOptions?: AuthorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.AuthorsPostResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/authors",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NewscatcherApi.AuthorsPostResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/authors");
    }
}
