/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const AuthorSearchRequestTo: core.serialization.Schema<
    serializers.AuthorSearchRequestTo.Raw,
    NewscatcherApi.AuthorSearchRequestTo
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.date()]);

export declare namespace AuthorSearchRequestTo {
    type Raw = string | string;
}
