// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "\"supply chain\" AND Amazon NOT China",
 *         search_in: "title_content, title_content_translated",
 *         include_translation_fields: true,
 *         predefined_sources: "top 50 US, top 20 GB",
 *         source_name: "sport,tech",
 *         sources: "nytimes.com,finance.yahoo.com",
 *         not_sources: "cnn.com,wsj.com",
 *         lang: "en,es",
 *         not_lang: "fr,de",
 *         countries: "US,CA",
 *         not_countries: "UK,FR",
 *         not_author_name: "John Doe, Jane Doe",
 *         from_: "2024-07-01T00:00:00Z",
 *         to_: "2024-01-01T00:00:00Z",
 *         published_date_precision: "full",
 *         by_parse_date: true,
 *         ranked_only: true,
 *         from_rank: 100,
 *         to_rank: 100,
 *         is_headline: true,
 *         is_opinion: true,
 *         is_paid_content: false,
 *         parent_url: "wsj.com/politics,wsj.com/tech",
 *         all_links: "https://aiindex.stanford.edu/report,https://www.stateof.ai",
 *         all_domain_links: "who.int,nih.gov",
 *         all_links_text: "Nvidia,Tesla",
 *         additional_domain_info: true,
 *         is_news_domain: true,
 *         news_type: "General News Outlets,Tech News and Updates",
 *         word_count_min: 300,
 *         word_count_max: 1000,
 *         page: 2,
 *         page_size: 50,
 *         clustering_enabled: true,
 *         clustering_threshold: 0.6,
 *         include_nlp_data: true,
 *         has_nlp: true,
 *         theme: "Finance,Tech",
 *         not_theme: "Crime,Sports",
 *         ORG_entity_name: "\"Apple Inc\" OR Microsoft",
 *         PER_entity_name: "\"Elon Musk\" OR \"Jeff Bezos\"",
 *         LOC_entity_name: "\"San Francisco\" OR \"New York City\"",
 *         MISC_entity_name: "AWS OR \"Microsoft Azure\"",
 *         title_sentiment_min: -0.5,
 *         title_sentiment_max: 0.5,
 *         content_sentiment_min: -0.5,
 *         content_sentiment_max: 0.5,
 *         iptc_tags: "20000199,20000209",
 *         not_iptc_tags: "20000205,20000209",
 *         iab_tags: "Business,Events",
 *         not_iab_tags: "Agriculture,Metals",
 *         custom_tags: "Tag1,Tag2",
 *         exclude_duplicates: true,
 *         robots_compliant: true
 *     }
 */
export interface SearchGetRequest {
    q: NewscatcherApi.Q;
    search_in?: NewscatcherApi.SearchIn;
    include_translation_fields?: NewscatcherApi.IncludeTranslationFields;
    /**
     * Predefined top news sources per country.
     *
     * Format: start with the word `top`, followed by the number of desired sources, and then the two-letter country code [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     *
     * Multiple countries with the number of top sources can be specified as a comma-separated string.
     */
    predefined_sources?: string;
    /**
     * Word or phrase to search within the source names. To specify multiple values, use a comma-separated string.
     *
     * **Note**: The search doesn't require an exact match and returns sources containing the specified terms in their names. You can use any word or phrase, like `"sport"` or `"new york times"`. For example, `"sport"` returns sources such as `"Motorsport"`, `"Dot Esport"`, and `"Tuttosport"`.
     */
    source_name?: string;
    /** One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as `finance.yahoo.com`, are also acceptable.To specify multiple sources, use a comma-separated string. */
    sources?: string;
    /** The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string. */
    not_sources?: string;
    /**
     * The language(s) of the search. The only accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To select multiple languages, use a comma-separated string.
     *
     * To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
     */
    lang?: string;
    /**
     * The language(s) to exclude from the search. The accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To exclude multiple languages, use a comma-separated string.
     *
     * To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
     */
    not_lang?: string;
    /**
     * The countries where the news publisher is located. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To select multiple countries, use a comma-separated string.
     *
     * To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
     */
    countries?: string;
    /**
     * The publisher location countries to exclude from the search. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To exclude multiple countries, use a comma-separated string.
     *
     * To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
     */
    not_countries?: string;
    /** The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string. */
    not_author_name?: string;
    from_?: NewscatcherApi.From;
    to_?: NewscatcherApi.To;
    published_date_precision?: NewscatcherApi.PublishedDatePrecision;
    by_parse_date?: NewscatcherApi.ByParseDate;
    sort_by?: NewscatcherApi.SortBy;
    ranked_only?: NewscatcherApi.RankedOnly;
    from_rank?: NewscatcherApi.FromRank;
    to_rank?: NewscatcherApi.ToRank;
    is_headline?: NewscatcherApi.IsHeadline;
    is_opinion?: NewscatcherApi.IsOpinion;
    is_paid_content?: NewscatcherApi.IsPaidContent;
    /** The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string. */
    parent_url?: string;
    /**
     * The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
     *
     * For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
     */
    all_links?: string;
    /**
     * The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
     *
     * For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
     */
    all_domain_links?: string;
    /**
     * The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.
     *
     * **Note**: When this parameter is used, the response includes the `all_links_data` field with detailed link information.
     *
     * To learn more, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
     */
    all_links_text?: string;
    additional_domain_info?: NewscatcherApi.AdditionalDomainInfo;
    is_news_domain?: NewscatcherApi.IsNewsDomain;
    news_domain_type?: NewscatcherApi.NewsDomainType;
    /**
     * Filters results based on the news type. Multiple types can be specified using a comma-separated string.
     *
     * For a complete list of available news types, see [Enumerated parameters > News type](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#news-type-news-type).
     */
    news_type?: string;
    word_count_min?: NewscatcherApi.WordCountMin;
    word_count_max?: NewscatcherApi.WordCountMax;
    page?: NewscatcherApi.Page;
    page_size?: NewscatcherApi.PageSize;
    clustering_enabled?: NewscatcherApi.ClusteringEnabled;
    clustering_variable?: NewscatcherApi.ClusteringVariable;
    clustering_threshold?: NewscatcherApi.ClusteringThreshold;
    include_nlp_data?: NewscatcherApi.IncludeNlpData;
    has_nlp?: NewscatcherApi.HasNlp;
    theme?: NewscatcherApi.Theme;
    not_theme?: NewscatcherApi.NotTheme;
    ORG_entity_name?: NewscatcherApi.OrgEntityName;
    PER_entity_name?: NewscatcherApi.PerEntityName;
    LOC_entity_name?: NewscatcherApi.LocEntityName;
    MISC_entity_name?: NewscatcherApi.MiscEntityName;
    title_sentiment_min?: NewscatcherApi.TitleSentimentMin;
    title_sentiment_max?: NewscatcherApi.TitleSentimentMax;
    content_sentiment_min?: NewscatcherApi.ContentSentimentMin;
    content_sentiment_max?: NewscatcherApi.ContentSentimentMax;
    /**
     * Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
     *
     * **Note**: The `iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
     */
    iptc_tags?: string;
    /**
     * Inverse of the `iptc_tags` parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
     *
     * **Note**: The `not_iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
     */
    not_iptc_tags?: string;
    /**
     * Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.
     *
     * **Note**: The `iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
     */
    iab_tags?: string;
    /**
     * Inverse of the `iab_tags` parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.
     *
     * **Note**: The `not_iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
     */
    not_iab_tags?: string;
    /**
     * Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:
     *
     * - `custom_tags.taxonomy=Tag1,Tag2`, where `taxonomy` is the taxonomy name and `Tag1,Tag2` is a comma-separated list of tag names.
     *
     * Example: `custom_tags.industry="Manufacturing,Logistics"`
     *
     * To learn more, see the [Custom tags](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags).
     */
    custom_tags?: string;
    exclude_duplicates?: NewscatcherApi.ExcludeDuplicates;
    robots_compliant?: NewscatcherApi.RobotsCompliant;
}
