// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "\"supply chain\" AND Amazon NOT China",
 *         search_in: "title_content, title_content_translated",
 *         include_translation_fields: true,
 *         predefined_sources: "top 100 US, top 5 GB",
 *         source_name: "sport",
 *         sources: "nytimes.com",
 *         not_sources: "cnn.com",
 *         lang: "en",
 *         not_lang: "fr",
 *         countries: "US",
 *         not_countries: "UK",
 *         not_author_name: "John Doe",
 *         from_: "2024-07-01T00:00:00Z",
 *         to_: "2024-07-01T00:00:00Z",
 *         parent_url: "https://www.washingtonpost.com/politics",
 *         all_links: "https://aiindex.stanford.edu/report",
 *         all_domain_links: "nvidia.com",
 *         news_type: "General News Outlets",
 *         include_nlp_data: true,
 *         has_nlp: true,
 *         theme: "Business,Finance",
 *         not_theme: "Crime",
 *         ORG_entity_name: "Apple",
 *         PER_entity_name: "Elon Musk",
 *         LOC_entity_name: "California",
 *         MISC_entity_name: "Bitcoin",
 *         iptc_tags: "20000199,20000209",
 *         not_iptc_tags: "20000205,20000209",
 *         iab_tags: "Business,Events",
 *         not_iab_tags: "Agriculture,Metals",
 *         custom_tags: "Tag1,Tag2,Tag3"
 *     }
 */
export interface SearchGetRequest {
    q: NewscatcherApi.Q;
    search_in?: NewscatcherApi.SearchIn;
    include_translation_fields?: NewscatcherApi.IncludeTranslationFields;
    /**
     * Predefined top news sources per country.
     *
     * Format: start with the word `top`, followed by the number of desired sources, and then the two-letter country code [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Multiple countries with the number of top sources can be specified as a comma-separated string.
     *
     * Examples:
     * - `"top 100 US"`
     * - `"top 33 AT"`
     * - `"top 50 US, top 20 GB"`
     * - `"top 33 AT, top 50 IT"`
     */
    predefined_sources?: string;
    /**
     * Word or phrase to search within the source names. To specify multiple values, use a comma-separated string.
     *
     * Example: `"sport, tech"`
     *
     * **Note**: The search doesn't require an exact match and returns sources containing the specified terms in their names. You can use any word or phrase, like `"sport"` or `"new york times"`. For example, `"sport"` returns sources such as `"Motorsport"`, `"Dot Esport"`, and `"Tuttosport"`.
     */
    source_name?: string;
    /**
     * One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as `finance.yahoo.com`, are also acceptable.To specify multiple sources, use a comma-separated string.
     *
     * Examples:
     * - `"nytimes.com"`
     * - `"theguardian.com, finance.yahoo.com"`
     */
    sources?: string;
    /**
     * The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.
     *
     * Example: `"cnn.com, wsj.com"`
     */
    not_sources?: string;
    /**
     * The language(s) of the search. The only accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To select multiple languages, use a comma-separated string.
     *
     * Example: `"en, es"`
     *
     * To learn more, see [Enumerated parameters > Language](/docs/v3/api-reference/overview/enumerated-parameters#language-lang-and-not-lang).
     */
    lang?: string;
    /**
     * The language(s) to exclude from the search. The accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To exclude multiple languages, use a comma-separated string.
     *
     * Example: `"fr, de"`
     *
     * To learn more, see [Enumerated parameters > Language](/docs/v3/api-reference/overview/enumerated-parameters#language-lang-and-not-lang).
     */
    not_lang?: string;
    /**
     * The countries where the news publisher is located. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To select multiple countries, use a comma-separated string.
     *
     * Example: `"US, CA"`
     *
     * To learn more, see [Enumerated parameters > Country](/docs/v3/api-reference/overview/enumerated-parameters#country-country-and-not-country).
     */
    countries?: string;
    /**
     * The publisher location countries to exclude from the search. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To exclude multiple countries, use a comma-separated string.
     *
     * Example:`"US, CA"`
     *
     * To learn more, see [Enumerated parameters > Country](/docs/v3/api-reference/overview/enumerated-parameters#country-country-and-not-country).
     */
    not_countries?: string;
    /**
     * The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.
     *
     * Example: `"John Doe, Jane Doe"`
     */
    not_author_name?: string;
    /**
     * The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text. The default time zone is UTC.
     *
     * Formats with examples:
     * - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
     * - YYYY-MM-dd: `2024-07-01`
     * - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
     * - YYYY/mm/dd: `2024/07/01`
     * - English phrases: `7 day ago`, `today`
     *
     * **Note**: By default, applied to the publication date of the article. To use the article's parse date instead, set the `by_parse_date` parameter to `true`.
     */
    from_?: NewscatcherApi.SearchGetRequestFrom;
    /**
     * The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text. The default time zone is UTC.
     *
     * Formats with examples:
     * - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
     * - YYYY-MM-dd: `2024-07-01`
     * - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
     * - YYYY/mm/dd: `2024/07/01`
     * - English phrases: `1 day ago`, `now`
     *
     * **Note**: By default, applied to the publication date of the article. To use the article's parse date instead, set the `by_parse_date` parameter to `true`.
     */
    to_?: NewscatcherApi.SearchGetRequestTo;
    /**
     * The precision of the published date. There are three types:
     * - `full`: The day and time of an article is correctly identified with the appropriate timezone.
     * - `timezone unknown`: The day and time of an article is correctly identified without timezone.
     * - `date`: Only the day is identified without an exact time.
     */
    published_date_precision?: NewscatcherApi.SearchGetRequestPublishedDatePrecision;
    /** If true, the `from_` and `to_` parameters use article parse dates instead of published dates. Additionally, the `parse_date` variable is added to the output for each article object. */
    by_parse_date?: boolean;
    /**
     * The sorting order of the results. Possible values are:
     * - `relevancy`: The most relevant results first.
     * - `date`: The most recently published results first.
     * - `rank`: The results from the highest-ranked sources first.
     */
    sort_by?: NewscatcherApi.SearchGetRequestSortBy;
    /** If true, limits the search to sources ranked in the top 1 million online websites. If false, includes unranked sources which are assigned a rank of 999999. */
    ranked_only?: boolean;
    /** The lowest boundary of the rank of a news website to filter by. A lower rank indicates a more popular source. */
    from_rank?: number;
    /** The highest boundary of the rank of a news website to filter by. A lower rank indicates a more popular source. */
    to_rank?: number;
    /** If true, only returns articles that were posted on the home page of a given news domain. */
    is_headline?: boolean;
    /** If true, returns only opinion pieces. If false, excludes opinion-based articles and returns news only. */
    is_opinion?: boolean;
    /** If false, returns only articles that have publicly available complete content. Some publishers partially block content, so this setting ensures that only full articles are retrieved. */
    is_paid_content?: boolean;
    /**
     * The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.
     *
     * Example: `"wsj.com/politics, wsj.com/tech"`
     */
    parent_url?: string;
    /**
     * The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
     *
     * Example: `"https://aiindex.stanford.edu/report, https://www.stateof.ai"`
     *
     * For more details, see [Search by URL](/docs/v3/documentation/how-to/search-by-url).
     */
    all_links?: string;
    /**
     * The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
     *
     * Example: `"who.int, nih.gov"`
     *
     * For more details, see [Search by URL](/docs/v3/documentation/how-to/search-by-url).
     */
    all_domain_links?: string;
    /**
     * If true, includes additional domain information in the response for each article:
     * - `is_news_domain`: Boolean indicating if the source is a news domain.
     * - `news_domain_type`: Type of news domain (e.g., `"Original Content"`).
     * - `news_type`: Category of news (e.g., `"News and Blogs"`).
     */
    additional_domain_info?: boolean;
    /** If true, filters results to include only news domains. */
    is_news_domain?: boolean;
    /**
     * Filters results based on the news domain type. Possible values are:
     * - `Original Content`: Sources that produce their own content.
     * - `Aggregator`: Sources that collect content from various other sources.
     * - `Press Releases`: Sources primarily publishing press releases.
     * - `Republisher`: Sources that republish content from other sources.
     * - `Other`: Sources that don't fit into main categories.
     */
    news_domain_type?: NewscatcherApi.SearchGetRequestNewsDomainType;
    /**
     * Filters results based on the news type. Multiple types can be specified using a comma-separated string.
     *
     * Example: `"General News Outlets,Tech News and Updates"`
     *
     * For a complete list of available news types, see [Enumerated parameters > News type](/docs/v3/api-reference/overview/enumerated-parameters#news-type-news-type).
     */
    news_type?: string;
    /** The minimum number of words an article must contain. To be used for avoiding articles with small content. */
    word_count_min?: number;
    /** The maximum number of words an article can contain. To be used for avoiding articles with large content. */
    word_count_max?: number;
    /**
     * The page number to scroll through the results. Use for pagination, as a single API response can return up to 1,000 articles.
     *
     * For details, see [How to paginate large datasets](https://www.newscatcherapi.com/docs/v3/documentation/how-to/paginate-large-datasets).
     */
    page?: number;
    /** The number of articles to return per page. */
    page_size?: number;
    /**
     * Determines whether to group similar articles into clusters. If true, the API returns clustered results.
     *
     * To learn more, see [Clustering news articles](/docs/v3/documentation/guides-and-concepts/clustering-news-articles).
     */
    clustering_enabled?: boolean;
    /**
     * Specifies which part of the article to use for determining similarity when clustering.
     *
     * Possible values are:
     * - `content`: Uses the full article content (default).
     * - `title`: Uses only the article title.
     * - `summary`: Uses the article summary.
     *
     * To learn more, see [Clustering news articles](/docs/v3/documentation/guides-and-concepts/clustering-news-articles).
     */
    clustering_variable?: NewscatcherApi.SearchGetRequestClusteringVariable;
    /**
     * Sets the similarity threshold for grouping articles into clusters. A lower value creates more inclusive clusters, while a higher value requires greater similarity between articles.
     *
     * Examples:
     * - `0.3`: Results in larger, more diverse clusters.
     * - `0.6`: Balances cluster size and article similarity (default).
     * - `0.9`: Creates smaller, tightly related clusters.
     *
     * To learn more, see [Clustering news articles](/docs/v3/documentation/guides-and-concepts/clustering-news-articles).
     */
    clustering_threshold?: number;
    include_nlp_data?: NewscatcherApi.IncludeNlpData;
    has_nlp?: NewscatcherApi.HasNlp;
    /**
     * Filters articles based on their general topic, as determined by NLP analysis. To select multiple themes, use a comma-separated string.
     *
     * Example: `"Finance, Tech"`
     *
     * **Note**: The `theme` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     *
     * Available options: `Business`, `Economics`, `Entertainment`, `Finance`, `Health`, `Politics`, `Science`, `Sports`, `Tech`, `Crime`, `Financial Crime`, `Lifestyle`, `Automotive`, `Travel`, `Weather`, `General`.
     */
    theme?: string;
    /**
     * Inverse of the `theme` parameter. Excludes articles based on their general topic, as determined by NLP analysis. To exclude multiple themes, use a comma-separated string.
     *
     * Example: `"Crime, Tech"`
     *
     * **Note**: The `not_theme` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     */
    not_theme?: string;
    /**
     * Filters articles that mention specific organization names, as identified by NLP analysis. To specify multiple organizations, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
     *
     * Example: `"Apple, Microsoft"`
     *
     * **Note**: The `ORG_entity_name` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
     */
    ORG_entity_name?: string;
    /**
     * Filters articles that mention specific person names, as identified by NLP analysis. To specify multiple names, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
     *
     * Example: `"Elon Musk, Jeff Bezos"`
     *
     * **Note**: The `PER_entity_name` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
     */
    PER_entity_name?: string;
    /**
     * Filters articles that mention specific location names, as identified by NLP analysis. To specify multiple locations, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
     *
     * Example: `"California, New York"`
     *
     * **Note**: The `LOC_entity_name` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
     */
    LOC_entity_name?: string;
    /**
     * Filters articles that mention other named entities not falling under person, organization, or location categories. Includes events, nationalities, products, works of art, and more. To specify multiple entities, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
     *
     * Example: `"Bitcoin, Blockchain"`
     *
     * **Note**: The `MISC_entity_name` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
     */
    MISC_entity_name?: string;
    /**
     * Filters articles based on the minimum sentiment score of their titles.
     *
     * Range is `-1.0` to `1.0`, where:
     * - Negative values indicate negative sentiment.
     * - Positive values indicate positive sentiment.
     * - Values close to 0 indicate neutral sentiment.
     *
     * **Note**: The `title_sentiment_min` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     */
    title_sentiment_min?: number;
    /**
     * Filters articles based on the maximum sentiment score of their titles.
     *
     * Range is `-1.0` to `1.0`, where:
     * - Negative values indicate negative sentiment.
     * - Positive values indicate positive sentiment.
     * - Values close to 0 indicate neutral sentiment.
     *
     * **Note**: The `title_sentiment_max` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     */
    title_sentiment_max?: number;
    /**
     * Filters articles based on the minimum sentiment score of their content.
     *
     * Range is `-1.0` to `1.0`, where:
     * - Negative values indicate negative sentiment.
     * - Positive values indicate positive sentiment.
     * - Values close to 0 indicate neutral sentiment.
     *
     * **Note**: The `content_sentiment_min` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     */
    content_sentiment_min?: number;
    /**
     * Filters articles based on the maximum sentiment score of their content.
     *
     * Range is `-1.0` to `1.0`, where:
     * - Negative values indicate negative sentiment.
     * - Positive values indicate positive sentiment.
     * - Values close to 0 indicate neutral sentiment.
     *
     * **Note**: The `content_sentiment_max` parameter is only available if NLP is included in your subscription plan.
     *
     * To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
     */
    content_sentiment_max?: number;
    /**
     * Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
     *
     * Example: `"20000199, 20000209"`
     *
     * **Note**: The `iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
     */
    iptc_tags?: string;
    /**
     * Inverse of the `iptc_tags` parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
     *
     * Example: `"20000205, 20000209"`
     *
     * **Note**: The `not_iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
     */
    not_iptc_tags?: string;
    /**
     * Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.
     *
     * Example: `"Business, Events"`
     *
     * **Note**: The `iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
     */
    iab_tags?: string;
    /**
     * Inverse of the `iab_tags` parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.
     *
     * Example: `"Agriculture, Metals"`
     *
     * **Note**: The `not_iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
     *
     * To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
     */
    not_iab_tags?: string;
    /**
     * Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:
     *
     * - `custom_tags.taxonomy=Tag1,Tag2,Tag3`, where `taxonomy` is the taxonomy name and `Tag1,Tag2,Tag3` is a comma-separated list of tags.
     *
     * Example: `custom_tags.industry="Manufacturing, Supply Chain, Logistics"`
     *
     * To learn more, see the [Custom tags](/docs/v3/documentation/guides-and-concepts/custom-tags).
     */
    custom_tags?: string;
    /**
     * If true, excludes duplicate and highly similar articles from the search results. If false, returns all relevant articles, including duplicates.
     *
     * To learn more, see [Articles deduplication](/docs/v3/documentation/guides-and-concepts/articles-deduplication).
     */
    exclude_duplicates?: boolean;
    /** If true, returns only articles/sources that comply with the publisher's robots.txt rules. If false, returns only articles/sources that do not comply with robots.txt rules. If omitted, returns all articles/sources regardless of compliance status. */
    robots_compliant?: boolean;
}
