/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const AggregationBy: core.serialization.Schema<serializers.AggregationBy.Raw, NewscatcherApi.AggregationBy> =
    core.serialization.enum_(["day", "hour", "month"]);

export declare namespace AggregationBy {
    export type Raw = "day" | "hour" | "month";
}
