/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { Authors } from "./Authors";
import { Journalists } from "./Journalists";
import { DtoResponsesMoreLikeThisResponseArticleResultAllLinks } from "./DtoResponsesMoreLikeThisResponseArticleResultAllLinks";
import { DtoResponsesMoreLikeThisResponseArticleResultAllDomainLinks } from "./DtoResponsesMoreLikeThisResponseArticleResultAllDomainLinks";
import { SimilarDocument } from "./SimilarDocument";

export const ArticleResult: core.serialization.ObjectSchema<
    serializers.ArticleResult.Raw,
    NewscatcherApi.ArticleResult
> = core.serialization.object({
    title: core.serialization.string(),
    author: core.serialization.string().optional(),
    authors: Authors.optional(),
    journalists: Journalists.optional(),
    publishedDate: core.serialization.property("published_date", core.serialization.string().optional()),
    publishedDatePrecision: core.serialization.property(
        "published_date_precision",
        core.serialization.string().optional()
    ),
    updatedDate: core.serialization.property("updated_date", core.serialization.string().optional()),
    updatedDatePrecision: core.serialization.property("updated_date_precision", core.serialization.string().optional()),
    parseDate: core.serialization.property("parse_date", core.serialization.string().optional()),
    link: core.serialization.string(),
    domainUrl: core.serialization.property("domain_url", core.serialization.string()),
    fullDomainUrl: core.serialization.property("full_domain_url", core.serialization.string()),
    nameSource: core.serialization.property("name_source", core.serialization.string().optional()),
    isHeadline: core.serialization.property("is_headline", core.serialization.string().optional()),
    paidContent: core.serialization.property("paid_content", core.serialization.boolean().optional()),
    extractionData: core.serialization.property("extraction_data", core.serialization.string()),
    country: core.serialization.string().optional(),
    rights: core.serialization.string().optional(),
    rank: core.serialization.number(),
    media: core.serialization.string().optional(),
    language: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    content: core.serialization.string(),
    titleTranslatedEn: core.serialization.property("title_translated_en", core.serialization.string().optional()),
    contentTranslatedEn: core.serialization.property("content_translated_en", core.serialization.string().optional()),
    wordCount: core.serialization.property("word_count", core.serialization.number().optional()),
    isOpinion: core.serialization.property("is_opinion", core.serialization.boolean().optional()),
    twitterAccount: core.serialization.property("twitter_account", core.serialization.string().optional()),
    allLinks: core.serialization.property(
        "all_links",
        DtoResponsesMoreLikeThisResponseArticleResultAllLinks.optional()
    ),
    allDomainLinks: core.serialization.property(
        "all_domain_links",
        DtoResponsesMoreLikeThisResponseArticleResultAllDomainLinks.optional()
    ),
    nlp: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    id: core.serialization.string(),
    score: core.serialization.number(),
    similarDocuments: core.serialization.property(
        "similar_documents",
        core.serialization.list(SimilarDocument).optional()
    ),
    customTags: core.serialization.property(
        "custom_tags",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
});

export declare namespace ArticleResult {
    interface Raw {
        title: string;
        author?: string | null;
        authors?: Authors.Raw | null;
        journalists?: Journalists.Raw | null;
        published_date?: string | null;
        published_date_precision?: string | null;
        updated_date?: string | null;
        updated_date_precision?: string | null;
        parse_date?: string | null;
        link: string;
        domain_url: string;
        full_domain_url: string;
        name_source?: string | null;
        is_headline?: string | null;
        paid_content?: boolean | null;
        extraction_data: string;
        country?: string | null;
        rights?: string | null;
        rank: number;
        media?: string | null;
        language?: string | null;
        description?: string | null;
        content: string;
        title_translated_en?: string | null;
        content_translated_en?: string | null;
        word_count?: number | null;
        is_opinion?: boolean | null;
        twitter_account?: string | null;
        all_links?: DtoResponsesMoreLikeThisResponseArticleResultAllLinks.Raw | null;
        all_domain_links?: DtoResponsesMoreLikeThisResponseArticleResultAllDomainLinks.Raw | null;
        nlp?: Record<string, unknown> | null;
        id: string;
        score: number;
        similar_documents?: SimilarDocument.Raw[] | null;
        custom_tags?: Record<string, unknown> | null;
    }
}
