/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { ArticleEntity } from "./ArticleEntity";

export const Articles: core.serialization.Schema<serializers.Articles.Raw, NewscatcherApi.Articles> =
    core.serialization.list(ArticleEntity);

export declare namespace Articles {
    type Raw = ArticleEntity.Raw[];
}
