/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const ArticleEntityAllDomainLinks: core.serialization.Schema<
    serializers.ArticleEntityAllDomainLinks.Raw,
    NewscatcherApi.ArticleEntityAllDomainLinks
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.string()),
    core.serialization.string(),
]);

export declare namespace ArticleEntityAllDomainLinks {
    type Raw = string[] | string;
}
