/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const ArticleEntityAllLinks: core.serialization.Schema<
    serializers.ArticleEntityAllLinks.Raw,
    NewscatcherApi.ArticleEntityAllLinks
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.string()),
    core.serialization.string(),
]);

export declare namespace ArticleEntityAllLinks {
    type Raw = string[] | string;
}
