/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const AuthorName: core.serialization.Schema<serializers.AuthorName.Raw, NewscatcherApi.AuthorName> =
    core.serialization.string();

export declare namespace AuthorName {
    type Raw = string;
}
