/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { Authors } from "./Authors";
import { Journalists } from "./Journalists";
import { BreakingNewsArticleEntityAllLinks } from "./BreakingNewsArticleEntityAllLinks";
import { BreakingNewsArticleEntityAllDomainLinks } from "./BreakingNewsArticleEntityAllDomainLinks";
import { NlpDataEntity } from "./NlpDataEntity";

export const BreakingNewsArticleEntity: core.serialization.ObjectSchema<
    serializers.BreakingNewsArticleEntity.Raw,
    NewscatcherApi.BreakingNewsArticleEntity
> = core.serialization.object({
    title: core.serialization.string(),
    author: core.serialization.string().optional(),
    authors: Authors.optional(),
    journalists: Journalists.optional(),
    publishedDate: core.serialization.property("published_date", core.serialization.string().optional()),
    publishedDatePrecision: core.serialization.property(
        "published_date_precision",
        core.serialization.string().optional(),
    ),
    updatedDate: core.serialization.property("updated_date", core.serialization.string().optional()),
    updatedDatePrecision: core.serialization.property("updated_date_precision", core.serialization.string().optional()),
    parseDate: core.serialization.property("parse_date", core.serialization.string().optional()),
    link: core.serialization.string(),
    domainUrl: core.serialization.property("domain_url", core.serialization.string()),
    fullDomainUrl: core.serialization.property("full_domain_url", core.serialization.string()),
    nameSource: core.serialization.property("name_source", core.serialization.string().optional()),
    isHeadline: core.serialization.property("is_headline", core.serialization.boolean().optional()),
    paidContent: core.serialization.property("paid_content", core.serialization.boolean().optional()),
    parentUrl: core.serialization.property("parent_url", core.serialization.string()),
    country: core.serialization.string().optional(),
    rights: core.serialization.string().optional(),
    rank: core.serialization.number(),
    media: core.serialization.string().optional(),
    language: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    content: core.serialization.string(),
    wordCount: core.serialization.property("word_count", core.serialization.number().optional()),
    isOpinion: core.serialization.property("is_opinion", core.serialization.boolean().optional()),
    twitterAccount: core.serialization.property("twitter_account", core.serialization.string().optional()),
    allLinks: core.serialization.property("all_links", BreakingNewsArticleEntityAllLinks.optional()),
    allDomainLinks: core.serialization.property("all_domain_links", BreakingNewsArticleEntityAllDomainLinks.optional()),
    nlp: NlpDataEntity.optional(),
    id: core.serialization.string(),
    score: core.serialization.number(),
    robotsCompliant: core.serialization.property("robots_compliant", core.serialization.boolean().optional()),
});

export declare namespace BreakingNewsArticleEntity {
    export interface Raw {
        title: string;
        author?: string | null;
        authors?: Authors.Raw | null;
        journalists?: Journalists.Raw | null;
        published_date?: string | null;
        published_date_precision?: string | null;
        updated_date?: string | null;
        updated_date_precision?: string | null;
        parse_date?: string | null;
        link: string;
        domain_url: string;
        full_domain_url: string;
        name_source?: string | null;
        is_headline?: boolean | null;
        paid_content?: boolean | null;
        parent_url: string;
        country?: string | null;
        rights?: string | null;
        rank: number;
        media?: string | null;
        language?: string | null;
        description?: string | null;
        content: string;
        word_count?: number | null;
        is_opinion?: boolean | null;
        twitter_account?: string | null;
        all_links?: BreakingNewsArticleEntityAllLinks.Raw | null;
        all_domain_links?: BreakingNewsArticleEntityAllDomainLinks.Raw | null;
        nlp?: NlpDataEntity.Raw | null;
        id: string;
        score: number;
        robots_compliant?: boolean | null;
    }
}
