/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { BreakingNewsArticleEntity } from "./BreakingNewsArticleEntity";

export const BreakingNewsEventEntity: core.serialization.ObjectSchema<
    serializers.BreakingNewsEventEntity.Raw,
    NewscatcherApi.BreakingNewsEventEntity
> = core.serialization.object({
    eventId: core.serialization.property("event_id", core.serialization.string()),
    articlesCount: core.serialization.property("articles_count", core.serialization.number()),
    articles: core.serialization.list(BreakingNewsArticleEntity),
});

export declare namespace BreakingNewsEventEntity {
    export interface Raw {
        event_id: string;
        articles_count: number;
        articles: BreakingNewsArticleEntity.Raw[];
    }
}
