/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const ClusteringEnabled: core.serialization.Schema<
    serializers.ClusteringEnabled.Raw,
    NewscatcherApi.ClusteringEnabled
> = core.serialization.boolean();

export declare namespace ClusteringEnabled {
    type Raw = boolean;
}
