/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { ArticleEntity } from "./ArticleEntity";

export const ClusterEntity: core.serialization.ObjectSchema<
    serializers.ClusterEntity.Raw,
    NewscatcherApi.ClusterEntity
> = core.serialization.object({
    clusterId: core.serialization.property("cluster_id", core.serialization.string()),
    clusterSize: core.serialization.property("cluster_size", core.serialization.number()),
    articles: core.serialization.list(ArticleEntity),
});

export declare namespace ClusterEntity {
    export interface Raw {
        cluster_id: string;
        cluster_size: number;
        articles: ArticleEntity.Raw[];
    }
}
