/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const ContentSentimentMax: core.serialization.Schema<
    serializers.ContentSentimentMax.Raw,
    NewscatcherApi.ContentSentimentMax
> = core.serialization.number();

export declare namespace ContentSentimentMax {
    export type Raw = number;
}
