/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const ContentSentimentMin: core.serialization.Schema<
    serializers.ContentSentimentMin.Raw,
    NewscatcherApi.ContentSentimentMin
> = core.serialization.number();

export declare namespace ContentSentimentMin {
    type Raw = number;
}
