/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, NewscatcherApi.Error_> =
    core.serialization.object({
        message: core.serialization.string(),
        statusCode: core.serialization.property("status_code", core.serialization.number()),
        status: core.serialization.string(),
    });

export declare namespace Error_ {
    interface Raw {
        message: string;
        status_code: number;
        status: string;
    }
}
