/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const IabTags: core.serialization.Schema<serializers.IabTags.Raw, NewscatcherApi.IabTags> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace IabTags {
    export type Raw = string | string[];
}
