/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const IsNewsDomain: core.serialization.Schema<serializers.IsNewsDomain.Raw, NewscatcherApi.IsNewsDomain> =
    core.serialization.boolean();

export declare namespace IsNewsDomain {
    type Raw = boolean;
}
