/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const Journalists: core.serialization.Schema<serializers.Journalists.Raw, NewscatcherApi.Journalists> =
    core.serialization.undiscriminatedUnion([
        core.serialization.list(core.serialization.string()),
        core.serialization.string(),
    ]);

export declare namespace Journalists {
    type Raw = string[] | string;
}
