/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const NamedEntityListItem: core.serialization.ObjectSchema<
    serializers.NamedEntityListItem.Raw,
    NewscatcherApi.NamedEntityListItem
> = core.serialization.object({
    entityName: core.serialization.property("entity_name", core.serialization.string().optional()),
    count: core.serialization.number().optional(),
});

export declare namespace NamedEntityListItem {
    export interface Raw {
        entity_name?: string | null;
        count?: number | null;
    }
}
