/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const NotAuthorName: core.serialization.Schema<serializers.NotAuthorName.Raw, NewscatcherApi.NotAuthorName> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace NotAuthorName {
    type Raw = string | string[];
}
