/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const NotTheme: core.serialization.Schema<serializers.NotTheme.Raw, NewscatcherApi.NotTheme> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace NotTheme {
    type Raw = string | string[];
}
