/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const OrgEntityName: core.serialization.Schema<serializers.OrgEntityName.Raw, NewscatcherApi.OrgEntityName> =
    core.serialization.string();

export declare namespace OrgEntityName {
    export type Raw = string;
}
