/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const PerEntityName: core.serialization.Schema<serializers.PerEntityName.Raw, NewscatcherApi.PerEntityName> =
    core.serialization.string();

export declare namespace PerEntityName {
    export type Raw = string;
}
