/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const Q: core.serialization.Schema<serializers.Q.Raw, NewscatcherApi.Q> = core.serialization.string();

export declare namespace Q {
    type Raw = string;
}
