/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const SimilarDocumentsNumber: core.serialization.Schema<
    serializers.SimilarDocumentsNumber.Raw,
    NewscatcherApi.SimilarDocumentsNumber
> = core.serialization.number();

export declare namespace SimilarDocumentsNumber {
    export type Raw = number;
}
