/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const SimilarDocument: core.serialization.ObjectSchema<
    serializers.SimilarDocument.Raw,
    NewscatcherApi.SimilarDocument
> = core.serialization.object({
    id: core.serialization.string(),
    score: core.serialization.number(),
    title: core.serialization.string(),
    link: core.serialization.string(),
});

export declare namespace SimilarDocument {
    interface Raw {
        id: string;
        score: number;
        title: string;
        link: string;
    }
}
