/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { AdditionalSourceInfo } from "./AdditionalSourceInfo";

export const SourceInfo: core.serialization.ObjectSchema<serializers.SourceInfo.Raw, NewscatcherApi.SourceInfo> =
    core.serialization.object({
        nameSource: core.serialization.property("name_source", core.serialization.string().optional()),
        domainUrl: core.serialization.property("domain_url", core.serialization.string()),
        logo: core.serialization.string().optional(),
        additionalInfo: core.serialization.property("additional_info", AdditionalSourceInfo.optional()),
    });

export declare namespace SourceInfo {
    export interface Raw {
        name_source?: string | null;
        domain_url: string;
        logo?: string | null;
        additional_info?: AdditionalSourceInfo.Raw | null;
    }
}
