/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";
import { SourcesResponseDtoSourcesItem } from "./SourcesResponseDtoSourcesItem";

export const SourcesResponseDto: core.serialization.ObjectSchema<
    serializers.SourcesResponseDto.Raw,
    NewscatcherApi.SourcesResponseDto
> = core.serialization.object({
    message: core.serialization.string(),
    sources: core.serialization.list(SourcesResponseDtoSourcesItem),
    userInput: core.serialization.property(
        "user_input",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
});

export declare namespace SourcesResponseDto {
    export interface Raw {
        message: string;
        sources: SourcesResponseDtoSourcesItem.Raw[];
        user_input: Record<string, unknown>;
    }
}
