/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const SourceUrl: core.serialization.Schema<serializers.SourceUrl.Raw, NewscatcherApi.SourceUrl> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace SourceUrl {
    type Raw = string | string[];
}
