/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const TimeFrameCount: core.serialization.ObjectSchema<
    serializers.TimeFrameCount.Raw,
    NewscatcherApi.TimeFrameCount
> = core.serialization.object({
    timeFrame: core.serialization.property("time_frame", core.serialization.date()),
    articleCount: core.serialization.property("article_count", core.serialization.number()),
});

export declare namespace TimeFrameCount {
    export interface Raw {
        time_frame: string;
        article_count: number;
    }
}
