/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const TitleSentimentMin: core.serialization.Schema<
    serializers.TitleSentimentMin.Raw,
    NewscatcherApi.TitleSentimentMin
> = core.serialization.number();

export declare namespace TitleSentimentMin {
    export type Raw = number;
}
