/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as NewscatcherApi from "../../api/index";
import * as core from "../../core";

export const WordCountMin: core.serialization.Schema<serializers.WordCountMin.Raw, NewscatcherApi.WordCountMin> =
    core.serialization.number();

export declare namespace WordCountMin {
    export type Raw = number;
}
