/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as NewscatcherApi from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export declare namespace SearchLink {
    interface Options {
        environment?: core.Supplier<environments.NewscatcherApiEnvironment | string>;
        /** Override the x-api-token header */
        apiToken: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-api-token header */
        apiToken?: string;
    }
}

export class SearchLink {
    constructor(protected readonly _options: SearchLink.Options) {}

    /**
     * This endpoint allows you to search for articles. You can search for articles by id(s) or link(s).
     *
     * @param {NewscatcherApi.SearchUrlGetRequest} request
     * @param {SearchLink.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     *
     * @example
     *     await client.searchLink.searchUrlGet({
     *         ids: "ids",
     *         links: "links"
     *     })
     */
    public async searchUrlGet(
        request: NewscatcherApi.SearchUrlGetRequest,
        requestOptions?: SearchLink.RequestOptions
    ): Promise<NewscatcherApi.SearchResponse> {
        const { ids, links, from: from_, to, page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        _queryParams["ids"] = ids;
        _queryParams["links"] = links;
        if (from_ != null) {
            _queryParams["from_"] = from_;
        }

        if (to != null) {
            _queryParams["to_"] = to;
        }

        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.NewscatcherApiEnvironment.Default,
                "api/search_by_link"
            ),
            method: "GET",
            headers: {
                "x-api-token": await core.Supplier.get(this._options.apiToken),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "newscatcher-sdk/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.SearchResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError();
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * This endpoint allows you to search for articles. You can search for articles by id(s) or link(s).
     *
     * @param {NewscatcherApi.SearchUrlRequest} request
     * @param {SearchLink.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     *
     * @example
     *     await client.searchLink.searchUrlPost()
     */
    public async searchUrlPost(
        request: NewscatcherApi.SearchUrlRequest = {},
        requestOptions?: SearchLink.RequestOptions
    ): Promise<NewscatcherApi.SearchResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.NewscatcherApiEnvironment.Default,
                "api/search_by_link"
            ),
            method: "POST",
            headers: {
                "x-api-token": await core.Supplier.get(this._options.apiToken),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "newscatcher-sdk/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchUrlRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.SearchResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError();
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
