/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const MoreLikeThisRequestTo: core.serialization.Schema<
    serializers.MoreLikeThisRequestTo.Raw,
    NewscatcherApi.MoreLikeThisRequestTo
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.date()]);

export declare namespace MoreLikeThisRequestTo {
    type Raw = string | string;
}
