/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const BreakingNewsGetRequestSortBy: core.serialization.Schema<
    serializers.BreakingNewsGetRequestSortBy.Raw,
    NewscatcherApi.BreakingNewsGetRequestSortBy
> = core.serialization.enum_(["relevancy", "date", "rank"]);

export declare namespace BreakingNewsGetRequestSortBy {
    export type Raw = "relevancy" | "date" | "rank";
}
