// This file was auto-generated by Fern from our API Definition.

import * as NewscatcherApi from "../../src/api/index";
import { NewscatcherApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AggregationClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            aggregations: { aggregation_count: [{ time_frame: "2024-12-31T00:00:00Z", article_count: 86 }] },
            user_input: { key: "value" },
        };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.aggregation.get({
            q: '"supply chain" AND Amazon NOT China',
            search_in: "title_content, title_content_translated",
            predefined_sources: "top 100 US, top 5 GB",
            sources: "nytimes.com",
            not_sources: "cnn.com",
            lang: "en",
            not_lang: "fr",
            countries: "US",
            not_countries: "UK",
            not_author_name: "John Doe",
            from_: "2024-07-01T00:00:00Z",
            to_: "2024-07-01T00:00:00Z",
            parent_url: "https://www.washingtonpost.com/politics",
            all_links: "https://aiindex.stanford.edu/report",
            all_domain_links: "nvidia.com",
            include_nlp_data: true,
            has_nlp: true,
            theme: "Business,Finance",
            not_theme: "Crime",
            ORG_entity_name: "Apple",
            PER_entity_name: "Elon Musk",
            LOC_entity_name: "California",
            MISC_entity_name: "Bitcoin",
            iptc_tags: "20000199,20000209",
            not_iptc_tags: "20000205,20000209",
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            aggregations: {
                aggregation_count: [
                    {
                        time_frame: "2024-12-31T00:00:00Z",
                        article_count: 86,
                    },
                ],
            },
            user_input: {
                key: "value",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(408)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = "string";
        server
            .mockEndpoint()
            .get("/api/aggregation_count")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.get({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });

    test("post (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: '"supply chain" AND Amazon NOT China', aggregation_by: "day" };
        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            aggregations: { aggregation_count: [{ time_frame: "2024-12-31T00:00:00Z", article_count: 86 }] },
            user_input: { key: "value" },
        };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.aggregation.post({
            q: '"supply chain" AND Amazon NOT China',
            aggregation_by: "day",
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            aggregations: {
                aggregation_count: [
                    {
                        time_frame: "2024-12-31T00:00:00Z",
                        article_count: 86,
                    },
                ],
            },
            user_input: {
                key: "value",
            },
        });
    });

    test("post (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("post (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("post (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("post (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(408)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("post (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("post (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("post (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { q: "q" };
        const rawResponseBody = "string";
        server
            .mockEndpoint()
            .post("/api/aggregation_count")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aggregation.post({
                q: "q",
            });
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });
});
