// This file was auto-generated by Fern from our API Definition.

import * as NewscatcherApi from "../../src/api/index";
import { NewscatcherApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BreakingNewsClient", () => {
    test("BreakingNews_get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            content: "content",
                            id: "id",
                            score: 1.1,
                            robots_compliant: true,
                        },
                    ],
                },
            ],
            user_input: { key: "value" },
        };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.breakingNews.breakingNewsGet({
            top_n_articles: 5,
            include_translation_fields: true,
            include_nlp_data: true,
            has_nlp: true,
            theme: "Business,Finance",
            not_theme: "Crime",
            ORG_entity_name: "Apple",
            PER_entity_name: "Elon Musk",
            LOC_entity_name: "California",
            MISC_entity_name: "Bitcoin",
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            content: "content",
                            id: "id",
                            score: 1.1,
                            robots_compliant: true,
                        },
                    ],
                },
            ],
            user_input: {
                key: "value",
            },
        });
    });

    test("BreakingNews_get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("BreakingNews_get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("BreakingNews_get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("BreakingNews_get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(408).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("BreakingNews_get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("BreakingNews_get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("BreakingNews_get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = "string";
        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });

    test("BreakingNews_post (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { sort_by: "relevancy", ranked_only: true, top_n_articles: 1 };
        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            content: "content",
                            id: "id",
                            score: 1.1,
                            robots_compliant: true,
                        },
                    ],
                },
            ],
            user_input: { key: "value" },
        };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.breakingNews.breakingNewsPost({
            sort_by: "relevancy",
            ranked_only: true,
            top_n_articles: 1,
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            content: "content",
                            id: "id",
                            score: 1.1,
                            robots_compliant: true,
                        },
                    ],
                },
            ],
            user_input: {
                key: "value",
            },
        });
    });

    test("BreakingNews_post (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("BreakingNews_post (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("BreakingNews_post (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("BreakingNews_post (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(408)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("BreakingNews_post (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("BreakingNews_post (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("BreakingNews_post (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = "string";
        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });
});
