// This file was auto-generated by Fern from our API Definition.

import * as NewscatcherApi from "../../src/api/index";
import { NewscatcherApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BreakingNewsClient", () => {
    test("breakingNewsGet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            id: "id",
                            score: 1.1,
                        },
                    ],
                },
            ],
            user_input: { key: "value" },
        };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.breakingNews.breakingNewsGet({
            ranked_only: true,
            from_rank: 100,
            to_rank: 100,
            page: 2,
            page_size: 50,
            top_n_articles: 5,
            include_translation_fields: true,
            include_nlp_data: true,
            has_nlp: true,
            theme: "Finance,Tech",
            not_theme: "Crime,Sports",
            ORG_entity_name: '"Apple Inc" OR Microsoft',
            PER_entity_name: '"Elon Musk" OR "Jeff Bezos"',
            LOC_entity_name: '"San Francisco" OR "New York City"',
            MISC_entity_name: 'AWS OR "Microsoft Azure"',
            title_sentiment_min: -0.5,
            title_sentiment_max: 0.5,
            content_sentiment_min: -0.5,
            content_sentiment_max: 0.5,
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            id: "id",
                            score: 1.1,
                        },
                    ],
                },
            ],
            user_input: {
                key: "value",
            },
        });
    });

    test("breakingNewsGet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("breakingNewsGet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("breakingNewsGet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("breakingNewsGet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(408).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("breakingNewsGet (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("breakingNewsGet (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("breakingNewsGet (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = "string";

        server.mockEndpoint().get("/api/breaking_news").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsGet();
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });

    test("breakingNewsPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { sort_by: "relevancy", ranked_only: true, top_n_articles: 1 };
        const rawResponseBody = {
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            id: "id",
                            score: 1.1,
                        },
                    ],
                },
            ],
            user_input: { key: "value" },
        };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.breakingNews.breakingNewsPost({
            sort_by: "relevancy",
            ranked_only: true,
            top_n_articles: 1,
        });
        expect(response).toEqual({
            status: "status",
            total_hits: 1,
            page: 1,
            total_pages: 1,
            page_size: 1,
            breaking_news_events: [
                {
                    event_id: "event_id",
                    articles_count: 1,
                    articles: [
                        {
                            title: "title",
                            link: "link",
                            domain_url: "domain_url",
                            full_domain_url: "full_domain_url",
                            parent_url: "parent_url",
                            rank: 1,
                            id: "id",
                            score: 1.1,
                        },
                    ],
                },
            ],
            user_input: {
                key: "value",
            },
        });
    });

    test("breakingNewsPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.BadRequestError);
    });

    test("breakingNewsPost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.UnauthorizedError);
    });

    test("breakingNewsPost (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.ForbiddenError);
    });

    test("breakingNewsPost (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(408)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.RequestTimeoutError);
    });

    test("breakingNewsPost (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.UnprocessableEntityError);
    });

    test("breakingNewsPost (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", status_code: 1, status: "status" };

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.TooManyRequestsError);
    });

    test("breakingNewsPost (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new NewscatcherApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = "string";

        server
            .mockEndpoint()
            .post("/api/breaking_news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.breakingNews.breakingNewsPost();
        }).rejects.toThrow(NewscatcherApi.InternalServerError);
    });
});
