/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchGetRequestNewsDomainType: core.serialization.Schema<
    serializers.SearchGetRequestNewsDomainType.Raw,
    NewscatcherApi.SearchGetRequestNewsDomainType
> = core.serialization.enum_(["Original Content", "Aggregator", "Press Releases", "Republisher", "Other"]);

export declare namespace SearchGetRequestNewsDomainType {
    export type Raw = "Original Content" | "Aggregator" | "Press Releases" | "Republisher" | "Other";
}
