/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchResponse } from "../../../types/SearchResponse";
import { ClusteringSearchResponse } from "../../../types/ClusteringSearchResponse";

export const SearchPostResponse: core.serialization.Schema<
    serializers.SearchPostResponse.Raw,
    NewscatcherApi.SearchPostResponse
> = core.serialization.undiscriminatedUnion([SearchResponse, ClusteringSearchResponse]);

export declare namespace SearchPostResponse {
    type Raw = SearchResponse.Raw | ClusteringSearchResponse.Raw;
}
