/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestTo: core.serialization.Schema<
    serializers.SearchRequestTo.Raw,
    NewscatcherApi.SearchRequestTo
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.date()]);

export declare namespace SearchRequestTo {
    type Raw = string | string;
}
