/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestToRank: core.serialization.Schema<
    serializers.SearchRequestToRank.Raw,
    NewscatcherApi.SearchRequestToRank
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace SearchRequestToRank {
    type Raw = string | number;
}
