/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestIsHeadline: core.serialization.Schema<
    serializers.SearchRequestIsHeadline.Raw,
    NewscatcherApi.SearchRequestIsHeadline
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.boolean()]);

export declare namespace SearchRequestIsHeadline {
    type Raw = string | boolean;
}
