/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SourcesRequest {
    lang?: unknown;
    countries?: unknown;
    predefinedSources?: unknown;
    includeAdditionalInfo?: boolean;
    fromRank?: number;
    toRank?: number;
    sourceName?: unknown;
    sourceUrl?: unknown;
    isNewsDomain?: boolean;
    newsDomainType?: unknown;
    newsType?: unknown;
}
