/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Search } from "./api/resources/search/client/Client";
import { Latestheadlines } from "./api/resources/latestheadlines/client/Client";
import { Authors } from "./api/resources/authors/client/Client";
import { SearchLink } from "./api/resources/searchLink/client/Client";
import { Searchsimilar } from "./api/resources/searchsimilar/client/Client";
import { Sources } from "./api/resources/sources/client/Client";
import { Subscription } from "./api/resources/subscription/client/Client";

export declare namespace NewscatcherApiClient {
    interface Options {
        environment?: core.Supplier<environments.NewscatcherApiEnvironment | string>;
        /** Override the x-api-token header */
        apiToken: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-api-token header */
        apiToken?: string;
    }
}

export class NewscatcherApiClient {
    constructor(protected readonly _options: NewscatcherApiClient.Options) {}

    protected _search: Search | undefined;

    public get search(): Search {
        return (this._search ??= new Search(this._options));
    }

    protected _latestheadlines: Latestheadlines | undefined;

    public get latestheadlines(): Latestheadlines {
        return (this._latestheadlines ??= new Latestheadlines(this._options));
    }

    protected _authors: Authors | undefined;

    public get authors(): Authors {
        return (this._authors ??= new Authors(this._options));
    }

    protected _searchLink: SearchLink | undefined;

    public get searchLink(): SearchLink {
        return (this._searchLink ??= new SearchLink(this._options));
    }

    protected _searchsimilar: Searchsimilar | undefined;

    public get searchsimilar(): Searchsimilar {
        return (this._searchsimilar ??= new Searchsimilar(this._options));
    }

    protected _sources: Sources | undefined;

    public get sources(): Sources {
        return (this._sources ??= new Sources(this._options));
    }

    protected _subscription: Subscription | undefined;

    public get subscription(): Subscription {
        return (this._subscription ??= new Subscription(this._options));
    }
}
