// This file was auto-generated by Fern from our API Definition.

import { AggregationClient } from "./api/resources/aggregation/client/Client.js";
import { AuthorsClient } from "./api/resources/authors/client/Client.js";
import { BreakingNewsClient } from "./api/resources/breakingNews/client/Client.js";
import { LatestheadlinesClient } from "./api/resources/latestheadlines/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { SearchLinkClient } from "./api/resources/searchLink/client/Client.js";
import { SearchsimilarClient } from "./api/resources/searchsimilar/client/Client.js";
import { SourcesClient } from "./api/resources/sources/client/Client.js";
import { SubscriptionClient } from "./api/resources/subscription/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace NewscatcherApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NewscatcherApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NewscatcherApiClient.Options>;
    protected _search: SearchClient | undefined;
    protected _latestheadlines: LatestheadlinesClient | undefined;
    protected _breakingNews: BreakingNewsClient | undefined;
    protected _authors: AuthorsClient | undefined;
    protected _searchLink: SearchLinkClient | undefined;
    protected _searchsimilar: SearchsimilarClient | undefined;
    protected _sources: SourcesClient | undefined;
    protected _aggregation: AggregationClient | undefined;
    protected _subscription: SubscriptionClient | undefined;

    constructor(options: NewscatcherApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get latestheadlines(): LatestheadlinesClient {
        return (this._latestheadlines ??= new LatestheadlinesClient(this._options));
    }

    public get breakingNews(): BreakingNewsClient {
        return (this._breakingNews ??= new BreakingNewsClient(this._options));
    }

    public get authors(): AuthorsClient {
        return (this._authors ??= new AuthorsClient(this._options));
    }

    public get searchLink(): SearchLinkClient {
        return (this._searchLink ??= new SearchLinkClient(this._options));
    }

    public get searchsimilar(): SearchsimilarClient {
        return (this._searchsimilar ??= new SearchsimilarClient(this._options));
    }

    public get sources(): SourcesClient {
        return (this._sources ??= new SourcesClient(this._options));
    }

    public get aggregation(): AggregationClient {
        return (this._aggregation ??= new AggregationClient(this._options));
    }

    public get subscription(): SubscriptionClient {
        return (this._subscription ??= new SubscriptionClient(this._options));
    }
}
