/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const NewscatcherApiEnvironment = {
    Default: "https://v3-api.newscatcherapi.com",
} as const;

export type NewscatcherApiEnvironment = typeof NewscatcherApiEnvironment.Default;
