// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../index.js";

export type PostLatestHeadlinesResponse = NewscatcherApi.SearchResponseDto | NewscatcherApi.ClusteredSearchResponseDto;
