/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as NewscatcherApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Searchsimilar {
    export interface Options {
        environment?: core.Supplier<environments.NewscatcherApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Operations to find similar articles.
 */
export class Searchsimilar {
    constructor(protected readonly _options: Searchsimilar.Options) {}

    /**
     * Searches for articles similar to a specified query.
     *
     * @param {NewscatcherApi.SearchSimilarGetRequest} request
     * @param {Searchsimilar.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.searchsimilar.get({
     *         q: "technology AND (Apple OR Microsoft) NOT Google",
     *         searchIn: "title_content, title_content_translated",
     *         includeTranslationFields: true,
     *         similarDocumentsFields: "title,summary",
     *         predefinedSources: "top 100 US, top 5 GB",
     *         from: "2024-07-01T00:00:00Z",
     *         to: "2024-07-01T00:00:00Z",
     *         includeNlpData: true,
     *         hasNlp: true,
     *         theme: "Business,Finance",
     *         notTheme: "Crime",
     *         nerName: "Tesla",
     *         iptcTags: "20000199,20000209",
     *         notIptcTags: "20000205,20000209",
     *         customTags: "Tag1,Tag2,Tag3"
     *     })
     */
    public get(
        request: NewscatcherApi.SearchSimilarGetRequest,
        requestOptions?: Searchsimilar.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchSimilarGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: NewscatcherApi.SearchSimilarGetRequest,
        requestOptions?: Searchsimilar.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchSimilarGetResponse>> {
        const {
            q,
            searchIn,
            includeTranslationFields,
            includeSimilarDocuments,
            similarDocumentsNumber,
            similarDocumentsFields,
            predefinedSources,
            sources,
            notSources,
            lang,
            notLang,
            countries,
            notCountries,
            from: from_,
            to,
            byParseDate,
            publishedDatePrecision,
            sortBy,
            rankedOnly,
            fromRank,
            toRank,
            isHeadline,
            isOpinion,
            isPaidContent,
            parentUrl,
            allLinks,
            allDomainLinks,
            wordCountMin,
            wordCountMax,
            page,
            pageSize,
            includeNlpData,
            hasNlp,
            theme,
            notTheme,
            nerName,
            titleSentimentMin,
            titleSentimentMax,
            contentSentimentMin,
            contentSentimentMax,
            iptcTags,
            notIptcTags,
            customTags,
            robotsCompliant,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["q"] = q;
        if (searchIn != null) {
            _queryParams["search_in"] = searchIn;
        }

        if (includeTranslationFields != null) {
            _queryParams["include_translation_fields"] = includeTranslationFields.toString();
        }

        if (includeSimilarDocuments != null) {
            _queryParams["include_similar_documents"] = includeSimilarDocuments.toString();
        }

        if (similarDocumentsNumber != null) {
            _queryParams["similar_documents_number"] = similarDocumentsNumber.toString();
        }

        if (similarDocumentsFields != null) {
            _queryParams["similar_documents_fields"] = similarDocumentsFields;
        }

        if (predefinedSources != null) {
            _queryParams["predefined_sources"] = predefinedSources;
        }

        if (sources != null) {
            _queryParams["sources"] = sources;
        }

        if (notSources != null) {
            _queryParams["not_sources"] = notSources;
        }

        if (lang != null) {
            _queryParams["lang"] = lang;
        }

        if (notLang != null) {
            _queryParams["not_lang"] = notLang;
        }

        if (countries != null) {
            _queryParams["countries"] = countries;
        }

        if (notCountries != null) {
            _queryParams["not_countries"] = notCountries;
        }

        if (from_ != null) {
            _queryParams["from_"] = from_.toISOString();
        }

        if (to != null) {
            _queryParams["to_"] = to.toISOString();
        }

        if (byParseDate != null) {
            _queryParams["by_parse_date"] = byParseDate.toString();
        }

        if (publishedDatePrecision != null) {
            _queryParams["published_date_precision"] =
                serializers.SearchSimilarGetRequestPublishedDatePrecision.jsonOrThrow(publishedDatePrecision, {
                    unrecognizedObjectKeys: "strip",
                });
        }

        if (sortBy != null) {
            _queryParams["sort_by"] = serializers.SearchSimilarGetRequestSortBy.jsonOrThrow(sortBy, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (rankedOnly != null) {
            _queryParams["ranked_only"] = rankedOnly.toString();
        }

        if (fromRank != null) {
            _queryParams["from_rank"] = fromRank.toString();
        }

        if (toRank != null) {
            _queryParams["to_rank"] = toRank.toString();
        }

        if (isHeadline != null) {
            _queryParams["is_headline"] = isHeadline.toString();
        }

        if (isOpinion != null) {
            _queryParams["is_opinion"] = isOpinion.toString();
        }

        if (isPaidContent != null) {
            _queryParams["is_paid_content"] = isPaidContent.toString();
        }

        if (parentUrl != null) {
            _queryParams["parent_url"] = parentUrl;
        }

        if (allLinks != null) {
            _queryParams["all_links"] = allLinks;
        }

        if (allDomainLinks != null) {
            _queryParams["all_domain_links"] = allDomainLinks;
        }

        if (wordCountMin != null) {
            _queryParams["word_count_min"] = wordCountMin.toString();
        }

        if (wordCountMax != null) {
            _queryParams["word_count_max"] = wordCountMax.toString();
        }

        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (includeNlpData != null) {
            _queryParams["include_nlp_data"] = includeNlpData.toString();
        }

        if (hasNlp != null) {
            _queryParams["has_nlp"] = hasNlp.toString();
        }

        if (theme != null) {
            _queryParams["theme"] = theme;
        }

        if (notTheme != null) {
            _queryParams["not_theme"] = notTheme;
        }

        if (nerName != null) {
            _queryParams["ner_name"] = nerName;
        }

        if (titleSentimentMin != null) {
            _queryParams["title_sentiment_min"] = titleSentimentMin.toString();
        }

        if (titleSentimentMax != null) {
            _queryParams["title_sentiment_max"] = titleSentimentMax.toString();
        }

        if (contentSentimentMin != null) {
            _queryParams["content_sentiment_min"] = contentSentimentMin.toString();
        }

        if (contentSentimentMax != null) {
            _queryParams["content_sentiment_max"] = contentSentimentMax.toString();
        }

        if (iptcTags != null) {
            _queryParams["iptc_tags"] = iptcTags;
        }

        if (notIptcTags != null) {
            _queryParams["not_iptc_tags"] = notIptcTags;
        }

        if (customTags != null) {
            _queryParams["custom_tags"] = customTags;
        }

        if (robotsCompliant != null) {
            _queryParams["robots_compliant"] = robotsCompliant.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search_similar",
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.2.0",
                "User-Agent": "newscatcher-sdk/1.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.SearchSimilarGetResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(
                        serializers.InternalServerError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling GET /api/search_similar.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Searches for articles similar to the specified query. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.SearchSimilarPostRequest} request
     * @param {Searchsimilar.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.searchsimilar.post({
     *         q: "artificial intelligence",
     *         includeSimilarDocuments: true,
     *         similarDocumentsNumber: 5
     *     })
     */
    public post(
        request: NewscatcherApi.SearchSimilarPostRequest,
        requestOptions?: Searchsimilar.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchSimilarPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__post(request, requestOptions));
    }

    private async __post(
        request: NewscatcherApi.SearchSimilarPostRequest,
        requestOptions?: Searchsimilar.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchSimilarPostResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search_similar",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.2.0",
                "User-Agent": "newscatcher-sdk/1.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchSimilarPostRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.SearchSimilarPostResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(
                        serializers.InternalServerError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling POST /api/search_similar.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-token": apiKeyValue };
    }
}
