// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NewscatcherApi from "../../../index.js";

export declare namespace SearchsimilarClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to find similar articles.
 */
export class SearchsimilarClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SearchsimilarClient.Options>;

    constructor(options: SearchsimilarClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Searches for articles similar to a specified query.
     *
     * @param {NewscatcherApi.SearchSimilarGetRequest} request
     * @param {SearchsimilarClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.searchsimilar.get({
     *         q: "\"supply chain\" AND Amazon NOT China",
     *         search_in: "title_content, title_content_translated",
     *         include_translation_fields: true,
     *         similar_documents_fields: "title,summary",
     *         predefined_sources: "top 100 US, top 5 GB",
     *         sources: "nytimes.com",
     *         not_sources: "cnn.com",
     *         lang: "en",
     *         not_lang: "fr",
     *         countries: "US",
     *         not_countries: "UK",
     *         from_: "2024-07-01T00:00:00Z",
     *         to_: "2024-07-01T00:00:00Z",
     *         parent_url: "https://www.washingtonpost.com/politics",
     *         all_links: "https://aiindex.stanford.edu/report",
     *         all_domain_links: "nvidia.com",
     *         include_nlp_data: true,
     *         has_nlp: true,
     *         theme: "Business,Finance",
     *         not_theme: "Crime",
     *         ner_name: "Tesla",
     *         iptc_tags: "20000199,20000209",
     *         not_iptc_tags: "20000205,20000209",
     *         custom_tags: "Tag1,Tag2,Tag3"
     *     })
     */
    public get(
        request: NewscatcherApi.SearchSimilarGetRequest,
        requestOptions?: SearchsimilarClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchSimilarGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: NewscatcherApi.SearchSimilarGetRequest,
        requestOptions?: SearchsimilarClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchSimilarGetResponse>> {
        const {
            q,
            search_in: searchIn,
            include_translation_fields: includeTranslationFields,
            include_similar_documents: includeSimilarDocuments,
            similar_documents_number: similarDocumentsNumber,
            similar_documents_fields: similarDocumentsFields,
            predefined_sources: predefinedSources,
            sources,
            not_sources: notSources,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            from_,
            to_: to,
            by_parse_date: byParseDate,
            published_date_precision: publishedDatePrecision,
            sort_by: sortBy,
            ranked_only: rankedOnly,
            from_rank: fromRank,
            to_rank: toRank,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ner_name: nerName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            custom_tags: customTags,
            robots_compliant: robotsCompliant,
        } = request;
        const _queryParams: Record<string, unknown> = {
            q,
            search_in: searchIn,
            include_translation_fields: includeTranslationFields,
            include_similar_documents: includeSimilarDocuments,
            similar_documents_number: similarDocumentsNumber,
            similar_documents_fields: similarDocumentsFields,
            predefined_sources: predefinedSources,
            sources,
            not_sources: notSources,
            lang,
            not_lang: notLang,
            countries,
            not_countries: notCountries,
            from_: from_ != null ? (typeof from_ === "string" ? from_ : toJson(from_)) : undefined,
            to_: to != null ? (typeof to === "string" ? to : toJson(to)) : undefined,
            by_parse_date: byParseDate,
            published_date_precision: publishedDatePrecision != null ? publishedDatePrecision : undefined,
            sort_by: sortBy != null ? sortBy : undefined,
            ranked_only: rankedOnly,
            from_rank: fromRank,
            to_rank: toRank,
            is_headline: isHeadline,
            is_opinion: isOpinion,
            is_paid_content: isPaidContent,
            parent_url: parentUrl,
            all_links: allLinks,
            all_domain_links: allDomainLinks,
            word_count_min: wordCountMin,
            word_count_max: wordCountMax,
            page,
            page_size: pageSize,
            include_nlp_data: includeNlpData,
            has_nlp: hasNlp,
            theme,
            not_theme: notTheme,
            ner_name: nerName,
            title_sentiment_min: titleSentimentMin,
            title_sentiment_max: titleSentimentMax,
            content_sentiment_min: contentSentimentMin,
            content_sentiment_max: contentSentimentMax,
            iptc_tags: iptcTags,
            not_iptc_tags: notIptcTags,
            custom_tags: customTags,
            robots_compliant: robotsCompliant,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search_similar",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NewscatcherApi.SearchSimilarGetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/search_similar");
    }

    /**
     * Searches for articles similar to the specified query. You can filter results by language, country, source, and more.
     *
     * @param {NewscatcherApi.SearchSimilarPostRequest} request
     * @param {SearchsimilarClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.searchsimilar.post({
     *         q: "\"supply chain\" AND Amazon NOT China",
     *         include_similar_documents: true,
     *         similar_documents_number: 5,
     *         page_size: 10
     *     })
     */
    public post(
        request: NewscatcherApi.SearchSimilarPostRequest,
        requestOptions?: SearchsimilarClient.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.SearchSimilarPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__post(request, requestOptions));
    }

    private async __post(
        request: NewscatcherApi.SearchSimilarPostRequest,
        requestOptions?: SearchsimilarClient.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.SearchSimilarPostResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/search_similar",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NewscatcherApi.SearchSimilarPostResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        _response.error.body as NewscatcherApi.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(_response.error.body as string, _response.rawResponse);
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/search_similar");
    }
}
