/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as NewscatcherApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace BreakingNews {
    export interface Options {
        environment?: core.Supplier<environments.NewscatcherApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Operations to retrieve breaking news articles.
 */
export class BreakingNews {
    constructor(protected readonly _options: BreakingNews.Options) {}

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     *
     * @param {NewscatcherApi.BreakingNewsGetRequest} request
     * @param {BreakingNews.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.breakingNews.breakingNewsGet({
     *         topNArticles: 5,
     *         includeTranslationFields: true,
     *         includeNlpData: true,
     *         hasNlp: true,
     *         theme: "Business,Finance",
     *         notTheme: "Crime"
     *     })
     */
    public breakingNewsGet(
        request: NewscatcherApi.BreakingNewsGetRequest = {},
        requestOptions?: BreakingNews.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.BreakingNewsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__breakingNewsGet(request, requestOptions));
    }

    private async __breakingNewsGet(
        request: NewscatcherApi.BreakingNewsGetRequest = {},
        requestOptions?: BreakingNews.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.BreakingNewsResponseDto>> {
        const {
            sortBy,
            rankedOnly,
            fromRank,
            toRank,
            page,
            pageSize,
            topNArticles,
            includeTranslationFields,
            includeNlpData,
            hasNlp,
            theme,
            notTheme,
            orgEntityName,
            perEntityName,
            locEntityName,
            miscEntityName,
            titleSentimentMin,
            titleSentimentMax,
            contentSentimentMin,
            contentSentimentMax,
            robotsCompliant,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (sortBy != null) {
            _queryParams["sort_by"] = serializers.BreakingNewsGetRequestSortBy.jsonOrThrow(sortBy, {
                unrecognizedObjectKeys: "strip",
            });
        }

        if (rankedOnly != null) {
            _queryParams["ranked_only"] = rankedOnly.toString();
        }

        if (fromRank != null) {
            _queryParams["from_rank"] = fromRank.toString();
        }

        if (toRank != null) {
            _queryParams["to_rank"] = toRank.toString();
        }

        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (topNArticles != null) {
            _queryParams["top_n_articles"] = topNArticles.toString();
        }

        if (includeTranslationFields != null) {
            _queryParams["include_translation_fields"] = includeTranslationFields.toString();
        }

        if (includeNlpData != null) {
            _queryParams["include_nlp_data"] = includeNlpData.toString();
        }

        if (hasNlp != null) {
            _queryParams["has_nlp"] = hasNlp.toString();
        }

        if (theme != null) {
            _queryParams["theme"] = theme;
        }

        if (notTheme != null) {
            _queryParams["not_theme"] = notTheme;
        }

        if (orgEntityName != null) {
            _queryParams["ORG_entity_name"] = orgEntityName;
        }

        if (perEntityName != null) {
            _queryParams["PER_entity_name"] = perEntityName;
        }

        if (locEntityName != null) {
            _queryParams["LOC_entity_name"] = locEntityName;
        }

        if (miscEntityName != null) {
            _queryParams["MISC_entity_name"] = miscEntityName;
        }

        if (titleSentimentMin != null) {
            _queryParams["title_sentiment_min"] = titleSentimentMin.toString();
        }

        if (titleSentimentMax != null) {
            _queryParams["title_sentiment_max"] = titleSentimentMax.toString();
        }

        if (contentSentimentMin != null) {
            _queryParams["content_sentiment_min"] = contentSentimentMin.toString();
        }

        if (contentSentimentMax != null) {
            _queryParams["content_sentiment_max"] = contentSentimentMax.toString();
        }

        if (robotsCompliant != null) {
            _queryParams["robots_compliant"] = robotsCompliant.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/breaking_news",
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.2.0",
                "User-Agent": "newscatcher-sdk/1.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.BreakingNewsResponseDto.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(
                        serializers.InternalServerError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling GET /api/breaking_news.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieves breaking news articles and sorts them based on specified criteria.
     *
     * @param {NewscatcherApi.BreakingNewsPostRequest} request
     * @param {BreakingNews.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NewscatcherApi.BadRequestError}
     * @throws {@link NewscatcherApi.UnauthorizedError}
     * @throws {@link NewscatcherApi.ForbiddenError}
     * @throws {@link NewscatcherApi.RequestTimeoutError}
     * @throws {@link NewscatcherApi.UnprocessableEntityError}
     * @throws {@link NewscatcherApi.TooManyRequestsError}
     * @throws {@link NewscatcherApi.InternalServerError}
     *
     * @example
     *     await client.breakingNews.breakingNewsPost({
     *         sortBy: "relevancy",
     *         page: 1,
     *         pageSize: 100,
     *         includeNlpData: true
     *     })
     */
    public breakingNewsPost(
        request: NewscatcherApi.BreakingNewsPostRequest = {},
        requestOptions?: BreakingNews.RequestOptions,
    ): core.HttpResponsePromise<NewscatcherApi.BreakingNewsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__breakingNewsPost(request, requestOptions));
    }

    private async __breakingNewsPost(
        request: NewscatcherApi.BreakingNewsPostRequest = {},
        requestOptions?: BreakingNews.RequestOptions,
    ): Promise<core.WithRawResponse<NewscatcherApi.BreakingNewsResponseDto>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NewscatcherApiEnvironment.Default,
                "api/breaking_news",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "newscatcher-sdk",
                "X-Fern-SDK-Version": "1.2.0",
                "User-Agent": "newscatcher-sdk/1.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.BreakingNewsPostRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.BreakingNewsResponseDto.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NewscatcherApi.BadRequestError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new NewscatcherApi.UnauthorizedError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new NewscatcherApi.ForbiddenError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 408:
                    throw new NewscatcherApi.RequestTimeoutError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new NewscatcherApi.UnprocessableEntityError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new NewscatcherApi.TooManyRequestsError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 500:
                    throw new NewscatcherApi.InternalServerError(
                        serializers.InternalServerError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NewscatcherApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NewscatcherApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.NewscatcherApiTimeoutError("Timeout exceeded when calling POST /api/breaking_news.");
            case "unknown":
                throw new errors.NewscatcherApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-token": apiKeyValue };
    }
}
