/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const AggregationGetRequestPublishedDatePrecision: core.serialization.Schema<
    serializers.AggregationGetRequestPublishedDatePrecision.Raw,
    NewscatcherApi.AggregationGetRequestPublishedDatePrecision
> = core.serialization.enum_(["full", "timezone unknown", "date"]);

export declare namespace AggregationGetRequestPublishedDatePrecision {
    type Raw = "full" | "timezone unknown" | "date";
}
