/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const AggregationGetRequestAggregationBy: core.serialization.Schema<
    serializers.AggregationGetRequestAggregationBy.Raw,
    NewscatcherApi.AggregationGetRequestAggregationBy
> = core.serialization.enum_(["day", "hour"]);

export declare namespace AggregationGetRequestAggregationBy {
    type Raw = "day" | "hour";
}
