/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const AggregationGetRequestSortBy: core.serialization.Schema<
    serializers.AggregationGetRequestSortBy.Raw,
    NewscatcherApi.AggregationGetRequestSortBy
> = core.serialization.enum_(["relevancy", "date", "rank"]);

export declare namespace AggregationGetRequestSortBy {
    export type Raw = "relevancy" | "date" | "rank";
}
