/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchUrlRequestTo: core.serialization.Schema<
    serializers.SearchUrlRequestTo.Raw,
    NewscatcherApi.SearchUrlRequestTo
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.date()]);

export declare namespace SearchUrlRequestTo {
    type Raw = string | string;
}
