/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as NewscatcherApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchUrlRequestFrom: core.serialization.Schema<
    serializers.SearchUrlRequestFrom.Raw,
    NewscatcherApi.SearchUrlRequestFrom
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.date()]);

export declare namespace SearchUrlRequestFrom {
    type Raw = string | string;
}
