// This file was auto-generated by Fern from our API Definition.

import type * as NewscatcherApi from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "\"supply chain\" AND Amazon NOT China",
 *         aggregation_by: "day"
 *     }
 */
export interface AggregationPostRequest {
    q: NewscatcherApi.Q;
    aggregation_by?: NewscatcherApi.AggregationBy;
    search_in?: NewscatcherApi.SearchIn;
    predefined_sources?: NewscatcherApi.PredefinedSources;
    sources?: NewscatcherApi.Sources;
    not_sources?: NewscatcherApi.NotSources;
    lang?: NewscatcherApi.Lang;
    not_lang?: NewscatcherApi.NotLang;
    countries?: NewscatcherApi.Countries;
    not_countries?: NewscatcherApi.NotCountries;
    not_author_name?: NewscatcherApi.NotAuthorName;
    from_?: NewscatcherApi.From;
    to_?: NewscatcherApi.To;
    published_date_precision?: NewscatcherApi.PublishedDatePrecision;
    by_parse_date?: NewscatcherApi.ByParseDate;
    sort_by?: NewscatcherApi.SortBy;
    ranked_only?: NewscatcherApi.RankedOnly;
    from_rank?: NewscatcherApi.FromRank;
    to_rank?: NewscatcherApi.ToRank;
    is_headline?: NewscatcherApi.IsHeadline;
    is_opinion?: NewscatcherApi.IsOpinion;
    is_paid_content?: NewscatcherApi.IsPaidContent;
    parent_url?: NewscatcherApi.ParentUrl;
    all_links?: NewscatcherApi.AllLinks;
    all_domain_links?: NewscatcherApi.AllDomainLinks;
    word_count_min?: NewscatcherApi.WordCountMin;
    word_count_max?: NewscatcherApi.WordCountMax;
    page?: NewscatcherApi.Page;
    page_size?: NewscatcherApi.PageSize;
    include_nlp_data?: NewscatcherApi.IncludeNlpData;
    has_nlp?: NewscatcherApi.HasNlp;
    theme?: NewscatcherApi.Theme;
    not_theme?: NewscatcherApi.NotTheme;
    ORG_entity_name?: NewscatcherApi.OrgEntityName;
    PER_entity_name?: NewscatcherApi.PerEntityName;
    LOC_entity_name?: NewscatcherApi.LocEntityName;
    MISC_entity_name?: NewscatcherApi.MiscEntityName;
    title_sentiment_min?: NewscatcherApi.TitleSentimentMin;
    title_sentiment_max?: NewscatcherApi.TitleSentimentMax;
    content_sentiment_min?: NewscatcherApi.ContentSentimentMin;
    content_sentiment_max?: NewscatcherApi.ContentSentimentMax;
    iptc_tags?: NewscatcherApi.IptcTags;
    not_iptc_tags?: NewscatcherApi.NotIptcTags;
    robots_compliant?: NewscatcherApi.RobotsCompliant;
}
